### ISSUE TITLE
Is it possible to use pino as an error output for assert mesages

### ISSUE THREAD

**Issue by Kostanos** [pinojs/pino#1040]
Can anyone help me to establish pino as a default error output for the assert library?

Example:
assert(0, 'My error message')

Instead of receive output:
```
AssertionError [ERR_ASSERTION]: My error message
    at Object.<anonymous> (/sb-products/test1.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: true,
  operator: '=='
}
```

I would like to get something like:
```
{ "level": 50, "msg": "My error message", ...}
```

Thx.

**Comment by mcollina** [comment]
No, this is not possible.
