### ISSUE TITLE
Pino.final don't work with pm2 

### ISSUE THREAD

**Issue by DoranYun** [pinojs/pino#1045]
When I caught a exit event, I want log something with pino.final, like

```javascript
const globalLogger = pino(options)
const createExitHandler = () => {
  return pino.final(globalLogger, (err, finalLogger, evt) => {
    finalLogger.error(err, `exit event caught: ${evt}`)
    process.exit(err ? 1 : 0)
  })
}
process.on('exit', () => createExitHandler()(null, 'exit'))
```

but I got an error:

```bash
Error: final requires a stream that has a flushSync method, such as pino.destination
    at Function.final (/Projects/cava/example/node_modules/pino/lib/tools.js:368:11)
    at createExitHandler (/Projects/cava/example/.yalc/@msfe/cava/lib/utils/Logger/exitHandler.js:10:27)
    at process.<anonymous> (/Projects/cava/example/.yalc/@msfe/cava/lib/utils/Logger/exitHandler.js:15:40)
    at process.emit (events.js:326:22)
    at process._fatalException (internal/process/execution.js:165:25)
    /Projects/cava/example/node_modules/pino/lib/tools.js:368
    throw Error('final requires a stream that has a flushSync method, such as pino.destination')
```

I start my server with PM2:

```bash
pm2-docker start ecosystem.json
```

The reason is PM2 overwrite  `process.stdout.write`

Is there any workaround for this?

**Comment by DoranYun** [comment]
the ecosystem.json :

```json
{
    "apps": [{
        "name": "mobile-example-ssr",
        "script": "./server.js",
        "min_uptime": 35000,
        "max_memory_restart": "1100M",
        "max_restarts": 10,
        "exp_backoff_restart_delay": 1000,
        "env": {
            "NODE_ENV": "production"
        },
        "env_production": {
            "NODE_ENV": "production"
        },
        "env_dev": {
            "NODE_ENV": "development"
        },
        "instances": 6,
        "exec_mode": "cluster"
    }]
}
```

**Comment by jsumners** [comment]
You'll need to supply your own stream or avoid mutating core objects.
