### ISSUE TITLE
Applying a logMethod hook always causes an error

### ISSUE THREAD

**Issue by Tohaker** [pinojs/pino#1144]
`pino` version: 6.13.3

I've followed the steps [in the documentation](https://github.com/pinojs/pino/blob/master/docs/api.md#logmethod) exactly, and even the most simple example causes the following error to be thrown:

```js
import pino from 'pino';

const logger = pino({
  hooks: {
    logMethod: (args, method, number) => {
      return method.apply(this, args);
    }
  }
});

logger.info('hello world');
```

```sh
this[writeSym](null, format(o, n, this[formatOptsSym]), level)
          ^

TypeError: Cannot read property 'Symbol(pino.write)' of undefined
    at LOG ([REDACTED]logger/node_modules/pino/lib/tools.js:57:11)
    at Pino.logMethod (file:///[REDACTED]logger/test/exec/logger.js:6:21)
```

Without the hook, everything works as expected, but I'm really not sure how to proceed.

**Comment by Tohaker** [comment]
Never mind, I realise now that using an arrow function doesn't have access to `this`. Replacing with a standard function fixes it.
