### ISSUE TITLE
Error: Cannot find module '#pino/file'

### ISSUE THREAD

**Issue by pan93412** [pinojs/pino#1158]
## Brief Description

I set up the minimum environment to run this example:

```
const pino = require('pino');
const transport = pino.transport({
        target: '#pino/file',
});
pino(transport);
```

But it turns out to show `Error: Cannot find module '#pino/file'`.

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '#pino/file'
Require stack:
- /private/tmp/test/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at fixTarget (/private/tmp/test/node_modules/pino/lib/transport.js:102:30)
    at Function.transport (/private/tmp/test/node_modules/pino/lib/transport.js:87:22)
    at Object.<anonymous> (/private/tmp/test/main.js:2:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/private/tmp/test/main.js' ]
}
```

## Reproducible Step

I'm in `darwin/arm64`.

```
$ node -v
v16.11.1
$ yarn add pino && cat << EOF >> main.js
const pino = require('pino');
const transport = pino.transport({
        target: '#pino/file',
});
pino(transport);
EOF
$ node main.js
```

**Comment by climba03003** [comment]
`#pino/file` is renamed to `pino/file`.

https://github.com/pinojs/pino/blob/fc291b7df7f35107afdfab4ccf2e2640e9094f21/examples/transport.js#L9-L28
