### ISSUE TITLE
`Error: end() failed` when using multiple instance of pino (default 'pino/file')

### ISSUE THREAD

**Issue by aduponchel** [pinojs/pino#1241]
* **OS**: WSL 2 through W10
* **Node**: v16.13.0
* **npm**: 8.1.0
* **pino**: 7.4.1

I have created the smallest code possible to reproduce easily.
My use case is more complex.
What I would like is : 
* a main logger that will log into STDOUT and a log file and errors in a specific log file
* a child logger that will log into STDOUT and a log file different from main
* main.log() should not write in child logs
* child.log() should write in main logs
So I use 2 instances of pino to achieve it. I can not use instance.child() because `{transport}` seems not to be a parameter of child instances.

It works but it terminate dirty with the following error.
Is there an alternative ?
However, if an external lib use pino like I currently do, it may have conflit, right ? 

## Step to reproduce

```js
const pino = require('pino');
const main = pino(
    {
      transport: {
        target: 'pino/file',
      },
    },
);

const child = pino(
    {
      transport: {
        target: 'pino/file',
      },
    },
);

main.info('Hello world');
main.error(new Error('Main Error'));

child.info('Hello Child');
child.error(new Error('Child Error'));
```

node demo.js | pino-pretty

```log
[1637948848359] INFO (25146 on ***): Hello world
[1637948848360] ERROR (25146 on ***): Main Error
    err: {
      "type": "Error",
      "message": "Main Error",
      "stack":
          Error: Main Error
              at Object.<anonymous> (/home/***/***/demo.js:54:12)
              at Module._compile (node:internal/modules/cjs/loader:1101:14)
              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
              at Module.load (node:internal/modules/cjs/loader:981:32)
              at Function.Module._load (node:internal/modules/cjs/loader:822:12)
              at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
              at node:internal/main/run_main_module:17:47
    }
[1637948848360] INFO (25146 on ***): Hello Child
[1637948848360] ERROR (25146 on ***): Child Error
    err: {
      "type": "Error",
      "message": "Child Error",
      "stack":
          Error: Child Error
              at Object.<anonymous> (/home/***/***/demo.js:57:13)
              at Module._compile (node:internal/modules/cjs/loader:1101:14)
              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
              at Module.load (node:internal/modules/cjs/loader:981:32)
              at Function.Module._load (node:internal/modules/cjs/loader:822:12)
              at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
              at node:internal/main/run_main_module:17:47
    }
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: end() failed
    at end (/home/***/***/node_modules/thread-stream/index.js:394:15)
    at ThreadStream.end (/home/***/***/node_modules/thread-stream/index.js:253:5)
    at autoEnd (/home/***/***/node_modules/pino/lib/transport.js:74:10)
    at process.wrap (/home/***/***/node_modules/on-exit-leak-free/index.js:10:7)
    at Object.onceWrapper (node:events:510:26)
    at process.emit (node:events:402:35)
Emitted 'error' event on ThreadStream instance at:
    at destroy (/home/***/***/node_modules/thread-stream/index.js:341:12)
    at end (/home/***/***/node_modules/thread-stream/index.js:407:5)
    at ThreadStream.end (/home/***/***/node_modules/thread-stream/index.js:253:5)
    [... lines matching original stack trace ...]
    at process.emit (node:events:402:35)
```

**Comment by mcollina** [comment]
This looks like a bug on our end as should terminate cleanly.

However I think you should refactor your code to only have one main logger or have two logger writing to different destinations.
