### ISSUE TITLE
prom-client test suite failed

### ISSUE THREAD

**Issue by phracek** [pinojs/pino#1256]
See traceback from our test suite:

```bash
> prom-client@14.0.1 test /opt/app-root/src
> npm run lint && npm run compile-typescript && npm run test-unit


> prom-client@14.0.1 lint /opt/app-root/src
> eslint .


> prom-client@14.0.1 compile-typescript /opt/app-root/src
> tsc --project .


> prom-client@14.0.1 test-unit /opt/app-root/src
> jest

PASS test/summaryTest.js
FAIL test/registerTest.js
  ● register › should have the same contentType as the module

    Cannot find module '../' from 'test/registerTest.js'

      611 | 
      612 | it('should have the same contentType as the module', () => {
    > 613 | const moduleWideContentType = require('../').contentType;
          |                               ^
      614 | expect(register.contentType).toEqual(moduleWideContentType);
      615 | });
      616 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (test/registerTest.js:613:33)

PASS test/histogramTest.js
PASS test/gaugeTest.js

[snip]

PASS test/metrics/heapSizeAndUsedTest.js
PASS test/metrics/gcTest.js
PASS test/metrics/processRequestsTest.js
PASS test/metrics/processHandlesTest.js
PASS test/metrics/processStartTimeTest.js
PASS test/metrics/processOpenFileDescriptorsTest.js
PASS test/validationTest.js

Summary of all failing tests
FAIL test/registerTest.js
  ● register › should have the same contentType as the module

    Cannot find module '../' from 'test/registerTest.js'

      611 | 
      612 | it('should have the same contentType as the module', () => {
    > 613 | const moduleWideContentType = require('../').contentType;
          |                               ^
      614 | expect(register.contentType).toEqual(moduleWideContentType);
      615 | });
      616 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (test/registerTest.js:613:33)

```

**Comment by mcollina** [comment]
I'm sorry but I think you opened it too the wrong repo. We have nothing to do with prom-client.

**Comment by phracek** [comment]
Correct. I have passed the wrong logs.
