### ISSUE TITLE
Wrapped Pino Libraries TypeError The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'node:internal/process/task_queues'

### ISSUE THREAD

**Issue by mkaufmaner** [pinojs/pino#1278]
When trying to wrap pino v7 within an opinionated logging library for my organization using pino v7, and importing it into a Framework with IoC containers, I get the following error;

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'node:internal/process/task_queues'
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1214:13)
    at transport (/nest-project/node_modules/pino/lib/transport.js:83:25)
    at normalizeArgs (/nest-project/node_modules/pino/lib/tools.js:409:16)
    at pino (/nest-project/node_modules/pino/pino.js:84:28)
    at Pino.createInstance (/nest-project/node_modules/@ofni/node-logger/dist/vendors/pino/classes/pino.class.js:76:34)
    at Pino.init (/nest-project/node_modules/@ofni/node-logger/dist/classes/wrapper.class.js:31:34)
    at new Pino (/nest-project/node_modules/@ofni/node-logger/dist/vendors/pino/classes/pino.class.js:26:14)
    at Logger.create (/nest-project/node_modules/@ofni/node-logger/dist/classes/logger.class.js:86:24)
    at new Logger (/nest-project/node_modules/@ofni/node-logger/dist/classes/logger.class.js:34:32)
    at InstanceWrapper.useFactory [as metatype] (/nest-project/node_modules/@ofni/nest-logger/dist/providers/logger-library.provider.js:12:16)
    at Injector.instantiateClass (/nest-project/node_modules/@nestjs/core/injector/injector.js:304:55)
    at callback (/nest-project/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Injector.resolveConstructorParams (/nest-project/node_modules/@nestjs/core/injector/injector.js:124:24)
    at Injector.loadInstance (/nest-project/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/nest-project/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 4)
    at InstanceLoader.createInstancesOfProviders (/nest-project/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at /nest-project/node_modules/@nestjs/core/injector/instance-loader.js:29:13
    at async Promise.all (index 6)
    at InstanceLoader.createInstances (/nest-project/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
```

I have tracked this down to the getCaller() following function; specifically where the function skips within `node_modules` when iterating through the callstack. See https://github.com/pinojs/pino/blob/master/lib/caller.js#L20

However, this is a problem when using IoC containers; See the following function and logs.

**caller.js**
```js
'use strict'

function noOpPrepareStackTrace (_, stack) {
  return stack
}

module.exports = function getCaller () {
  const originalPrepare = Error.prepareStackTrace
  Error.prepareStackTrace = noOpPrepareStackTrace
  const stack = new Error().stack
  Error.prepareStackTrace = originalPrepare

  if (!Array.isArray(stack)) {
    return undefined
  }

  for (const entry of stack.slice(2)) {
    const file = entry ? entry.getFileName() : undefined

    if (file) {
      console.log('getCaller file: ' + file);
      if (file.indexOf('node_modules') === -1) {
        console.log('getCaller RETURN file: ' + file);
        return file
      }
    }
  }
}
```

**output**
```
getCaller file: /nest-project/node_modules/@ofni/node-logger/dist/vendors/pino/classes/pino.class.js
getCaller file: /nest-project/node_modules/@ofni/node-logger/dist/classes/wrapper.class.js
getCaller file: /nest-project/node_modules/@ofni/node-logger/dist/vendors/pino/classes/pino.class.js
getCaller file: /nest-project/node_modules/@ofni/node-logger/dist/classes/logger.class.js
getCaller file: /nest-project/node_modules/@ofni/node-logger/dist/classes/logger.class.js
getCaller file: /nest-project/node_modules/@ofni/nest-logger/dist/providers/logger-library.provider.js
getCaller file: /nest-project/node_modules/@nestjs/core/injector/injector.js
getCaller file: /nest-project/node_modules/@nestjs/core/injector/injector.js
getCaller file: node:internal/process/task_queues
getCaller RETURN file: node:internal/process/task_queues
```

~~I am recommending you either remove the check for `node_modules` or implement logic to verify you are returning an absolute file path and then reiterating without checking for `node_modules`.~~

@jsumners 
I am thinking about opening a PR that either removes the check for `node_modules` or implements logic to verify that the value being returned is an absolute file path. Then, if nothing is returned, execute a second iteration through the stack trace without checking for `node_modules`.

**Comment by mcollina** [comment]
Can you please upload a reproducible example? Thanks!

(A PR with a fix would be ok too)

**Comment by jsumners** [comment]
> I am recommending you either remove the check for `node_modules` or implement logic to verify you are returning an absolute file path and then reiterating without checking for `node_modules`.

This statement is a demanding statement. Please do not demand things. Instead, provide constructive suggestions.

**Comment by mkaufmaner** [comment]
@jsumners
I am thinking about opening a PR that either removes the check for node_modules or implements logic to verify that the value being returned is an absolute file path. Then, if nothing is returned, execute a second iteration through the stack trace without checking for node_modules.

@mcollina 
More than happy to open a PR. An example of this may just be trying to get nestjs-pino to work.

@jsumners @mcollina 
I see that the `get-caller-file` dependency was moved away from in this [commit](https://github.com/pinojs/pino/pull/1267/files). What was the purpose of this change and why wasn't the logic from  https://github.com/stefanpenner/get-caller-file/blob/master/index.ts used? Why does this new logic exclude node_modules?

Thank you.

**Comment by jsumners** [comment]
Please review the associated PR. I am sure there is information within it to answer your questions.

**Comment by mcollina** [comment]
A PR that fixes this without breaking the functionality we added recently would be good. However I suspect it won't be as easy as you describe.

A better solution is to retain the full array of callers and iterate over them until the dependency is found.

**Comment by doums** [comment]
Hi, just to let you know I'm in the same case and I get the same error, downgrading to `7.5.1` fix it.

**Comment by mcollina** [comment]
Should be fixed by https://github.com/pinojs/pino/pull/1276. Closing.
