### ISSUE TITLE
passing logger methods to a function

### ISSUE THREAD

**Issue by ahmafi** [pinojs/pino#1281]
Is this a bad idea to pass logger methods as function arguments?

I was trying something like this:

index.js:
```javascript
const logger = require("./logger");

const fn = (loggerMethod) => {
  loggerMethod("hello");
};

fn(logger.fatal);
```

logger.js:
```javascript
const pino = require("pino");

let transport = pino.transport({
  target: "pino/file",
  options: { destination: "server.log" },
});

const logger = pino(transport);

module.exports = logger;

```

But it throws an error:
```
/home/amir/projects/tests/pino-test/node_modules/pino/lib/levels.js:25
      const stream = this[streamSym]
                         ^

TypeError: Cannot read properties of undefined (reading 'Symbol(pino.stream)')
    at /home/amir/projects/tests/pino-test/node_modules/pino/lib/levels.js:25:26
    at fn (/home/amir/projects/tests/pino-test/index.js:5:3)
    at Object.<anonymous> (/home/amir/projects/tests/pino-test/index.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.1.0
```

How am I supposed to tell a function to log at a specific level? Image a utility function that checks if a file exists or not, and based on who is calling this function I want to create logs at different levels, one check if fails might be a fatal and the other might be an error.

**Comment by jsumners** [comment]
I don't know why you wouldn't pass in the logger itself:

```js
function doesStuff({ logger = require('abstract-logging') }) {
  log.fatal('uh oh')
}
```

But if you really want do pass the method, you should bind the instance:

```js
doesStuff(logger.fatal.bind(logger))
```

**Comment by ahmafi** [comment]
Thanks, bind was what I wanted.

> I don't know why you wouldn't pass in the logger itself:

take a look at this example:
```javascript
const checkFile = (filename, loggerMethod) => {
  fs.access(filename, fs.constants.F_OK, (a) => {
    if (a) {
      loggerMethod(`${filename} not found`);
    }
  });
};

// if index.js doesn't exist we should exit the program
checkFile("index.js", logger.fatal.bind(logger));

// if not-an-important-file doesn't exist we report an error, but the program can still run
checkFile("not-an-important-file", logger.error.bind(logger));
```

**Comment by jsumners** [comment]
You're making it more complicated than it needs to be:

```js
try {
  somethingNotFatal()
} catch (cause) {
  const error = Error('could not do a thing')
  error.cause = cause
  logger.error(error)
}
```
