### ISSUE TITLE
broken on Node v12

### ISSUE THREAD

**Issue by borisovg** [pinojs/pino#1484]
Broken on Node v12 without a major version change or mention in release notes.

Using example code from top of README:

```
home/george/test/pino/node_modules/on-exit-leak-free/index.js:11
const registry = new FinalizationRegistry(clear)
                 ^

ReferenceError: FinalizationRegistry is not defined
    at Object.<anonymous> (/home/george/test/pino/node_modules/on-exit-leak-free/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/george/test/pino/node_modules/pino/lib/tools.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

This is caused by https://github.com/pinojs/pino/pull/1474 (upgrading the `on-exit-leak-free` dependency).

**Comment by jsumners** [comment]
`pino@8` does not support Node 12 https://github.com/pinojs/pino/blob/40fb2646995d0d07cfcd851ad32d62f9daf1b8ca/.github/workflows/ci.yml#L45
