### ISSUE TITLE
err errors are creating duplicated msg properties

### ISSUE THREAD

**Issue by leon-volq** [pinojs/pino#1650]
I'm using `"pino": "8.10.0"`

This script will output two logs with two "msg" properties each

```js
import pino from 'pino'

const log = pino()

log.info({ msg: 'hello', err: new Error('world') })

log.info({ err: new Error('world'), msg: 'hello' })
```
Log one
```json
{
    "level": 30,
    "time": 1676678480988,
    "pid": 17643,
    "hostname": "leons-matebook",
    "msg": "hello",
    "err": {
        "type": "Error",
        "message": "world",
        "stack": "Error: world\n    at file:///home/leon/Documents/martianbitcoins/game-servers/core-game/api/test-pino.js:5:31\n    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)\n    at async Promise.all (index 0)\n    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)\n    at async loadESM (node:internal/process/esm_loader:91:5)\n    at async handleMainPromise (node:internal/modules/run_main:65:12)"
    },
    "msg": "world"
}
```

Log two
```json
{
    "level": 30,
    "time": 1676678480989,
    "pid": 17643,
    "hostname": "leons-matebook",
    "err": {
        "type": "Error",
        "message": "world",
        "stack": "Error: world\n    at file:///home/leon/Documents/martianbitcoins/game-servers/core-game/api/test-pino.js:7:17\n    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)\n    at async Promise.all (index 0)\n    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)\n    at async loadESM (node:internal/process/esm_loader:91:5)\n    at async handleMainPromise (node:internal/modules/run_main:65:12)"
    },
    "msg": "hello",
    "msg": "world"
}
```

And then when parsing the JSON only the last "msg" value will remain.

Is a bit confusing since I had to start using "notice" key instead of "msg" key when logging errors, and I have to keep that in mind or my "msg" will be "eaten up"

Is this intended?
Is it documented and I missed it? 
If this is intended what is your recommended approach? 

Thank you for the great library! :heart:

**Comment by mcollina** [comment]
I think this is an unwanted consequence of this line: https://github.com/pinojs/pino/blob/eafbc906a0cb065eb2da05edaebe144d838dcab2/lib/proto.js#L190-L193

I think we should also check if the object has a `msg` property.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by leon-volq** [comment]
Hello @mcollina, Thank you, yes working on a PR
