### ISSUE TITLE
Force pino to act synchronously in transport

### ISSUE THREAD

**Issue by punowo** [pinojs/pino#1651]
Hello. This is not really an issue and it might just be me not paying enough attention to the documentation. Please feel free to close this if needed. 

I'm in a pseudo-monorepo scenario where I'm trying to have something wrapper around pino.js to serve some specific requirements and I'm trying to implement a basic call counter for when some parts or the entire log repeats itself. I'm using a temporary file to store the last X or so log lines, or at least I'm attempting to do this because I couldn't think of something better. 

```javascript
const logger = require("pino")({
  customLevels: {
    fine: 10,
    info: 30,
    warn: 40,
    severe: 55,
  },
  useOnlyCustomLevels: true,
  level: "fine",
  transport: {
    target: "./prettyTransport.js",

  },
  options: {
    base: undefined,
    timestamp: false,
    colorize: true,
  },
});

logger.fine("Alabama");
logger.fine("Texas");

module.exports = {
  logger,
};
```

```javascript
const temporaryDirectory = require("os").tmpdir();
const fs = require("fs");
const path = require("node:path");
const { DateTime } = require("luxon");

module.exports = (opts) =>
  require("pino-pretty")({
    ...opts,
    include: "",
    messageFormat: (log, messageKey) => {
      let callCounter;
      let lvlLabel = "FINE"; // default fine label
      switch (log.level) {
        case 55:
          lvlLabel = "SEVERE";
          break;
        case 40:
          lvlLabel = "WARN";
          break;
        case 30:
          lvlLabel = "INFO";
          break;
      }

      const partialLog = `${lvlLabel}|${log.hierarchy}|${log.featureName}|${log.fundamentalOperationName}|${log.user}|${log.input}|${log[messageKey]}|${log.outputDestination}`;
      callCounter = handleCallCounter(partialLog);
      console.log("AFTER CALL COUNTER FUNCTION");

      if (!log.hierarchy) log.hierarchy = "";
      if (!log.featureName) log.featureName = "";
      if (!log.fundamentalOperationName) log.fundamentalOperationName = "";
      if (!log.user) log.user = "";
      if (!log.input) log.input = "";
      if (!log.outputDestination) log.outputDestination = "";
      console.log(`${log.time}|${partialLog}|${callCounter}`);
      return `${log.time}|${partialLog}|${callCounter}`;
    },
  });

const handleCallCounter = (partialLog) => {
  // get a path for a temporary log file
  const lastLoggerLinesFilePath = path.join(
    temporaryDirectory,
    path.sep,
    "lastLoggerLines"
  );
  // get current unix timestamp and a past unix timestamp based on how much time should
  // call counter cover
  const currentUnixTimeStamp = DateTime.now().toUnixInteger();
  const pastUnixTimeStamp = DateTime.now()
    .minus({ seconds: 4 }) // ideally this should not be hardcoded
    .toUnixInteger();
  // add current log information at the end of the file and if the file is emtpy, create it
  try {
    fs.appendFileSync(
      lastLoggerLinesFilePath,
      `${currentUnixTimeStamp}|${partialLog}\r\n`,
      {
        encoding: "utf8",
      }
    );
  } catch (err) {
    if (err.errno == -4058 && err.code == "ENOENT" && err.syscall == "open") {
      fs.appendFileSync(
        lastLoggerLinesFilePath,
        `${currentUnixTimeStamp}|${partialLog}\r\n`,
        {
          encoding: "utf8",
          flag: "w",
        }
      );
    } else {
      console.error(err);
    }
  }
  // read the file
  const lastLoggerLines = fs.readFileSync(lastLoggerLinesFilePath, "utf-8");
  lastLoggerLines.split("\r\n").forEach((o) => {
    console.log(o);
  });
};
```
The problem I'm having is that it seems pino will not wait for `handleCallCounter` to finish. ( the lines with longer unix timestamp are the ones from pino, formatted by the transport ) 
```
node .\src\index.js
1676905102|FINE|undefined|undefined|undefined|undefined|undefined|Alabama|undefined
1676905102258|FINE|undefined|undefined|undefined|undefined|undefined|Alabama|undefined|undefined

1676905102258|FINE|undefined|undefined|undefined|undefined|undefined|Texas|undefined|undefined
AFTER CALL COUNTER FUNCTION
1676905102258|FINE|undefined|undefined|undefined|undefined|undefined|Alabama|undefined|undefined
1676905102|FINE|undefined|undefined|undefined|undefined|undefined|Alabama|undefined
1676905102|FINE|undefined|undefined|undefined|undefined|undefined|Texas|undefined

AFTER CALL COUNTER FUNCTION
1676905102258|FINE|undefined|undefined|undefined|undefined|undefined|Texas|undefined|undefined
```

In case I'm not doing something wrong is there any way to force a sync behaviour unto pino or this wrapper in this case similar to what I could find for pino.destination ? 
I'm also going to attach a screenshot after a slight modification, maybe it's more clear. 

![Screenshot_1](https://user-images.githubusercontent.com/96526435/220148988-032ccada-9a69-459d-89cf-62b845522046.png)

As you can see in the screenshot, pino returns during the second console.log of the function `handleCallCounter` even though the function hasn't finished running.

**Comment by mcollina** [comment]
A few notes: `console.log` in workers is extremely weird, it sends the data back to the main thread for writing it out. Use [`sonic-boom`](https://github.com/pinojs/sonic-boom) instead.

**Comment by punowo** [comment]
> A few notes: `console.log` in workers is extremely weird, it sends the data back to the main thread for writing it out. Use [`sonic-boom`](https://github.com/pinojs/sonic-boom) instead.

I'm going to take a look at it tomorrow, I stumbled upon it but I thought I don't need it. Thanks.

**Comment by mcollina** [comment]
No, it should be sync.

**Comment by punowo** [comment]
> A few notes: `console.log` in workers is extremely weird, it sends the data back to the main thread for writing it out. Use [`sonic-boom`](https://github.com/pinojs/sonic-boom) instead.

```javascript
  // read the file
  const sonic = new SonicBoom({ fd: process.stdout.fd });
  const lastLoggerLines = fs.readFileSync(lastLoggerLinesFilePath, "utf-8");
  lastLoggerLines.split("\r\n").forEach((o) => {
    sonic.write("hello sonic\n");
  });
```
```
 node .\src\index.js
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: SonicBoom supports only file descriptors and files
    at new SonicBoom (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\sonic-boom\index.js:121:11)
    at C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\src\prettyTransport.js:78:19
    at Array.forEach (<anonymous>)
    at handleCallCounter (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\src\prettyTransport.js:77:33)
    at messageFormat (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\src\prettyTransport.js:27:21)
    at prettifyMessage (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\pino-pretty\lib\utils.js:282:17)
    at pretty (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\pino-pretty\index.js:122:31)
    at Transform.transform [as _transform] (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\pino-pretty\index.js:217:22)
    at Transform._write (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\readable-stream\lib\internal\streams\transform.js:153:8)
    at writeOrBuffer (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\readable-stream\lib\internal\streams\writable.js:334:12)
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (C:\Users\AntonCiprianVasilach\Development\plus-internals\libraries\logger\node_modules\thread-stream\index.js:360:12)
    at process.processImmediate (node:internal/timers:476:21)

Node.js v18.14.1
```

The example works for me, but I think this also should work, right ? Am I using it wrong ?

**Comment by mcollina** [comment]
`process.stdout` is not the standard output stream in workers, so you'd need to pass the file descriptor directly:

```js
  // read the file
  const sonic = new SonicBoom({ fd: 1 });
  const lastLoggerLines = fs.readFileSync(lastLoggerLinesFilePath, "utf-8");
  lastLoggerLines.split("\r\n").forEach((o) => {
    sonic.write("hello sonic\n");
  });
```

**Comment by punowo** [comment]
> `process.stdout` is not the standard output stream in workers, so you'd need to pass the file descriptor directly:
> 
> ```js
>   // read the file
>   const sonic = new SonicBoom({ fd: 1 });
>   const lastLoggerLines = fs.readFileSync(lastLoggerLinesFilePath, "utf-8");
>   lastLoggerLines.split("\r\n").forEach((o) => {
>     sonic.write("hello sonic\n");
>   });
> ```

Thank you. Can you point me in a direction where I can learn more about this ? I'm thinking of also using sonic-boom for other stuff.

**Comment by mcollina** [comment]
Here it is: https://nodejs.org/api/worker_threads.html#synchronous-blocking-of-stdio
