### ISSUE TITLE
breaks

### ISSUE THREAD

**Issue by mayeaux** [pinojs/pino#1660]
```
node:internal/validators:123
      throw new ERR_OUT_OF_RANGE(name, `>= ${min} && <= ${max}`, value);
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "fd" is out of range. It must be >= 0 && <= 2147483647. Received -1
    at Object.write (node:fs:819:8)
    at actualWrite (/home/aj/generate-subtitles-server/node_modules/sonic-boom/index.js:409:8)
    at SonicBoom.write (/home/aj/generate-subtitles-server/node_modules/sonic-boom/index.js:262:5)
    at Object.write (/home/aj/generate-subtitles-server/node_modules/pino/lib/multistream.js:71:16)
    at Pino.write (/home/aj/generate-subtitles-server/node_modules/pino/lib/proto.js:215:10)
    at Pino.LOG [as error] (/home/aj/generate-subtitles-server/node_modules/pino/lib/tools.js:62:21)
    at process.<anonymous> (/home/aj/generate-subtitles-server/app.js:185:10)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:149:25) {
  code: 'ERR_OUT_OF_RANGE'
}

```

```
var pino = require('pino')
var multistream = pino.multistream

const streams = [
  { stream: pino.destination({ dest: process.cwd() + '/logs/error.log' }), level: 'error' },
  { stream: process.stderr, level: 'error' },
  { stream: process.stdout, level: 'info' },
  { stream: pino.destination({ dest: process.cwd() + '/logs/info.log' }), level: 'info' },
];


var opts = {
  levels: {
    silent: Infinity,
    fatal: 60,
    error: 50,
    warn: 50,
    info: 30,
    debug: 20,
    trace: 10
  },
  dedupe: true,
}

var log = pino({
  level: 'trace' // this MUST be set at the lowest level of the
  // destinations
}, multistream(streams, opts))

// log.debug('this will be written ONLY to process.stdout')
// log.info('this will be written ONLY to process.stdout')
// log.error('this will be written ONLY to process.stderr')
// log.fatal('this will be written ONLY to process.stderr')

const error = new Error('Example error')
log.error(new Error('Example error'));

module.exports = log
```

**Comment by mcollina** [comment]
Thanks for reporting!

Unfortunately I can't reproduce your problem. We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by acdibble** [comment]
I encountered this error when the directory for the logs didn't exist and the `mkdir` option wasn't set.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by acdibble** [comment]
Sorry, I was trying to say I think everything is working as intended and was trying to provide more context to the OP or anyone else who may come here from a google search.

If you encounter this error it likely means that the file descriptor is invalid because the file couldn't be opened. Check that the `mkdir` option is set and that the process has permissions to write to the directory.
