### ISSUE TITLE
Getting "the worker has exited" error with pino-socket transport

### ISSUE THREAD

**Issue by pocketcolin** [pinojs/pino#1662]
Because of a "the worker has exited" error, my transport is failing to run and send the data to my Logstash service over TCP. I've seen a few other issues posted here with this error message, but they are all closed at this point so I'm opening a new one. One commonality between those issues is that people had a lot of trouble replicating it and the same is true here. My current guess is that it has something to do with the connection timing out as it seems like when I first deploy my server it works fine but if I don't hit the server with anything for even 30 minutes I'll get that error again. Once the error starts, the only way to get the transport working again is to restart the server. I also have been unable to replicate this locally. Lastly, I tried the suggestion of using `pino.multistream` which was mentioned in a previous issue, but that did not help. Any ideas for what I can test or thoughts on what might be wrong here?

Setup
```
nodejs: 16.14.0
pino: 8.11.0
pino-socket: 7.3.0
@elastic/ecs-pino-format: 1.3.0
```

`logger.ts`
```
import pino from 'pino'
import ecsPinoFormat from '@elastic/ecs-pino-format'

let logger: pino.Logger
const initLogger = () => {
    if (logger) {
        return logger
    }

    const lsHost = process.env.LOGSTASH_HOST
    const lsPort = process.env.LOGSTASH_PORT
    const ecsFormat = ecsPinoFormat()
    const loggerTransport = 
        pino.transport((lsHost && lsPort)
            ? {
                target: 'pino-socket',
                options: {
                    address: lsHost,
                    port: lsPort,
                    mode: 'tcp',
                },
            }
            : {
                target: 'pino-pretty',
            }
        )
    logger = pino(ecsFormat, loggerTransport)

    return logger
}

const initializedLogger = initLogger()

export default initializedLogger
```

The full stack trace:
```
error: Uncaught internal server error. the worker has exited {"domainThrown":true,"stack":"Error: the worker has exited
    at ThreadStream.write (/opt/render/project/src/node_modules/thread-stream/index.js:229:19)
    at Pino.write (/opt/render/project/src/node_modules/pino/lib/proto.js:215:10)
    at Pino.LOG [as info] (/opt/render/project/src/node_modules/pino/lib/tools.js:71:21)
    at ServerResponse.<anonymous> (/opt/render/project/src/dist/index.js:100:30)
    at /opt/render/project/src/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:49
    at AsyncLocalStorage.run (node:async_hooks:322:14)
    at AsyncLocalStorageRunContextManager.with (/opt/render/project/src/node_modules/elastic-apm-node/lib/instrumentation/run-context/AsyncLocalStorageRunContextManager.js:57:36)
    at ServerResponse.wrapper (/opt/render/project/src/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:23)
    at ServerResponse.emit (node:events:532:35)
    at ServerResponse.emit (node:domain:537:15)
    at LegacyContextManager.runInContext (/opt/render/project/src/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at ServerResponse.wrapped [as emit] (/opt/render/project/src/node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
    at onFinish (node:_http_outgoing:830:10)
    at callback (node:internal/streams/writable:552:21)
    at afterWrite (node:internal/streams/writable:497:5)
    at afterWriteTick (node:internal/streams/writable:484:10)
    at runInContextCb (/opt/render/project/src/node_modules/newrelic/lib/shim/shim.js:1315:22)
    at LegacyContextManager.runInContext (/opt/render/project/src/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at Shim.applySegment (/opt/render/project/src/node_modules/newrelic/lib/shim/shim.js:1305:25)
    at wrapper (/opt/render/project/src/node_modules/newrelic/lib/shim/shim.js:1861:17)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}
```

**Comment by pocketcolin** [comment]
Closing this because adding the `pino-socket` option of `reconnect: true` fixed this specific issue but created a new one. Continuing discussion of that issue here: https://github.com/pinojs/pino-socket/issues/96
