### ISSUE TITLE
`exposes faux stdSerializers` test fail on node v19.9.0

### ISSUE THREAD

**Issue by rluvaton** [pinojs/pino#1690]
The tests fail on node v19.9.0 on master:

```
 FAIL  test/browser.test.js
 ✖ pino.stdSerializers.errWithCause

  test: test/browser.test.js
  operator: ok
  expected: true
  actual: undefined
  at: Test.<anonymous> (/Users/rluvaton/dev/tmp/pino/test/browser.test.js:101:5)
  stack: >-
    Error: pino.stdSerializers.errWithCause
        at Test.assert [as _assert] (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:312:48)
        at Test.bound [as _assert] (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:95:17)
        at Test.assert (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:431:7)
        at bound (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:95:17)
        at Test.<anonymous> (/Users/rluvaton/dev/tmp/pino/test/browser.test.js:101:5)
        at Test.bound [as _cb] (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:95:17)
        at Test.run (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:115:28)
        at Test.bound [as run] (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/test.js:95:17)
        at Immediate.next [as _onImmediate] (/Users/rluvaton/dev/tmp/pino/node_modules/tape/lib/results.js:157:7)
        at process.processImmediate (node:internal/timers:478:21)
```

reproduce:

```bash
nvm install 19.9.0
nvm use 19.9.0
npm i
npm test
```

this cause the CITGM tests in node to fail.

related PR:
- https://github.com/nodejs/node/pull/47413

**Comment by rluvaton** [comment]
So you say it's https://github.com/pinojs/pino-std-serializers issue?

**Comment by jsumners** [comment]
> So you say it's https://github.com/pinojs/pino-std-serializers issue?

No. It's an issue here.

**Comment by jsumners** [comment]
We need someone to dig into the timeouts happening in our test suite https://github.com/pinojs/pino/pull/1691#issuecomment-1504009718
