### ISSUE TITLE
Pretty formatting fails when a custom level is added

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#172]
```js
'use strict'

const pino = require('pino')
const pretty = pino.pretty()
pretty.pipe(process.stdout)
const log = pino({level: 'foo', levelVal: 35}, pretty)

log.foo('hello')
```

Yields:
```
% node foo.js
/private/tmp/16/node_modules/pino/pretty.js:131
    return levelColors[value.level](levels[value.level])
                                   ^

TypeError: levelColors[value.level] is not a function
    at asColoredLevel (/private/tmp/16/node_modules/pino/pretty.js:131:36)
    at DestroyableTransform.mapLine [as mapper] (/private/tmp/16/node_modules/pino/pretty.js:106:48)
    at DestroyableTransform.transform [as _transform] (/private/tmp/16/node_modules/split2/index.js:33:21)
    at DestroyableTransform.Transform._read (/private/tmp/16/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/private/tmp/16/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/private/tmp/16/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/private/tmp/16/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/private/tmp/16/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at EventEmitter.Pino.write (/private/tmp/16/node_modules/pino/pino.js:306:17)
    at EventEmitter.LOG (/private/tmp/16/node_modules/pino/pino.js:423:10)
```

**Comment by jsumners** [comment]
Fixed by #173
