### ISSUE TITLE
Cannot build Next.js application with pino and any transports

### ISSUE THREAD

**Issue by clempat** [pinojs/pino#1738]
Node: v18.16.0
Pino: 8.14.1
Pino-pretty: 10.0.0 

I am migrating a project to use the new App Router from Next.js. When I try to build the project, I get the following error:
```
Error: Cannot find module '/#redacted#/.next/server/chunks/lib/worker.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:197:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:298:10)
    at Worker.[kOnMessage] (node:internal/worker:309:37)
    at MessagePort.<anonymous> (node:internal/worker:205:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```
This error occurs as soon I had a transport to the logger. I believe it has to do with worker thread.

Here is a bare Next.js project with pino to reproduce the issue:
https://github.com/clempat/nextjs-pinojs

Doing `yarn && yarn build` results to a similar error:

```
Node.js v18.16.0
[   =] - info Generating static pages (3/4)
node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/#redacted#/.next/server/chunks/lib/worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:164:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/#redacted#/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/#redacted#/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.

```
I am open to any suggestions and happy to help.

**Comment by k-ruben** [comment]
encountered the same problem while migrating to the new app router

**Comment by jsumners** [comment]
Can you help me understand how this is a Pino specific issue?

**Comment by clempat** [comment]
I am, unfortunately, not sure if it relies on Pino or NextJS. 

What I am certain is that the project build and run as soon we do not use any Pino transports.

Maybe I should take an other approach with the App directory which won't includes Pino or any Pino transports but I believe it is good to raise the issue that any Pino transports does not work with the new NextJS Router.

**Comment by mcollina** [comment]
Please read https://github.com/pinojs/pino/blob/master/docs/bundling.md, what you are experiencing is described there with a potential solution for webpack.
