### ISSUE TITLE
obj.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#180]
Found this deep inside our server logs

```
obj.hasOwnProperty is not a function
    at EventEmitter.asJson (/Users/ronagy/Projects/github/nxtedition/nxt-storage/node_modules/pino/pino.js:175:15)
    at EventEmitter.Pino.write (/Users/ronagy/Projects/github/nxtedition/nxt-storage/node_modules/pino/pino.js:224:16)
    at EventEmitter.LOG (/Users/ronagy/Projects/github/nxtedition/nxt-storage/node_modules/pino/lib/tools.js:116:10)
```

Not sure how to reproduce it.

**Comment by jsumners** [comment]
Did it start with a specific version of Pino?

**Comment by mcollina** [comment]
It would help to know what are you logging to cause this, otherwise it would be very hard to track.

**Comment by davidmarkclements** [comment]
ok I know what it is

```js
var o = Object.create(null)
o.foo = 1
pino.info(o) // TypeError: obj.hasOwnProperty is not a function
```

I think we'll have to do a check for hasOwnProperty - if it it's not there we don't need to do the check
