### ISSUE TITLE
broken on Node 16 & 18 

### ISSUE THREAD

**Issue by Progressive-Programmer** [pinojs/pino#1809]
/Users/amansingh/Documents/__WorkSpace__/KeeperAI/New MSTeams/MSTeams-Bot/node_modules/on-exit-leak-free/index.js:11
const registry = new FinalizationRegistry(clear)
                 ^

ReferenceError: FinalizationRegistry is not defined
    at Object.<anonymous> (/Users/amansingh/Documents/__WorkSpace__/KeeperAI/New MSTeams/MSTeams-Bot/node_modules/on-exit-leak-free/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/amansingh/Documents/__WorkSpace__/KeeperAI/New MSTeams/MSTeams-Bot/node_modules/pino/lib/tools.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
[nodemon] app crashed - waiting for file changes before starting...

Tested with node 14, 16, 18

package.json
    "dependencies": {
        "@microsoft/adaptivecards-tools": "^1.0.0",
        "botbuilder": "^4.18.0",
        "restify": "^11.1.0"
    },
    "devDependencies": {
        "env-cmd": "^10.1.0",
        "nodemon": "^2.0.7"
    }

**Comment by mcollina** [comment]
Thanks for reporting! `FinalizationRegistry` is available in Node v18, v16 and v14. There is something odd in your application that removes this global.

You can test it with `node -e 'console.log(FinalizationRegistry)'`

**Comment by Progressive-Programmer** [comment]
node -e 'console.log(FinalizationRegistry)'
[Function: FinalizationRegistry]

I got this

**Comment by mcollina** [comment]
Which means that the Node.js version you are using has `FinalizationRegistry`. I'm not sure what Node.js version you are using to get the error above, but that's not a clean v14, v16 or v18 release.

**Comment by Progressive-Programmer** [comment]
What do you suggest  I should try to resolve this ?

**Comment by mcollina** [comment]
I have literally no clue, it's something on your system or how you run this application. Try assembling a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem. I would recommend a separate github repo with all the steps.

**Comment by curiousercreative** [comment]
@mcollina should this issue be closed?

**Comment by jsumners** [comment]
Closing due to lack of response.
