### ISSUE TITLE
After building 'unable to determine transport target for "@axiomhq/pino"' due to "cjs" folder being deleted after build

### ISSUE THREAD

**Issue by AliD201** [pinojs/pino#1964]
Hello ! 
thanks for the great package! 

I have been trying to connect to axiom and send logs. while in development everything works fine. 
but in deployment I keep receiving the error
```
unable to determine transport target for "@axiomhq/pino"
  at fixTarget (J:\...redecated...\.output\server\node_modules\pino\lib\transport.js:146:13)
  at Function.transport (J:\...redecated...\.output\server\node_modules\pino\lib\transport.js:116:22)
```

am using Nuxt3 with vite. 
i did try to turn off treeshaking in `nuxt.config.ts` 
```js
  vite:{
    build:{
      rollupOptions:{
      // Exclude the package from tree shaking
      // external: ['@axiomhq']
      treeshake: false

      }
    }
  },
```

but still the same issue. 

Here is my logger code: 
```js
import '@axiomhq/pino'
import pino from 'pino';

const logger = pino(
  { level: 'info',
    redact: {
      paths:["email","phone","mobile_number","customerMobile","TS_customer_mobile","TS_customer_email","TS_staff_member_mobile","TS_staff_member_email","user_mobile","user_email"],
      // remove: true
    }
  },
  pino.transport({
      target: '@axiomhq/pino',
      options: {
        dataset: useRuntimeConfig().axiomDataset,
        token: useRuntimeConfig().axiomToken,
        // dataset: process.env.AXIOM_DATASET,
        // token: process.env.AXIOM_TOKEN,
      },
  }
  ),
);
export {logger}
```

Note: it works just fine with pino-pretty. but am not sure what is happening in the building step. 

i spent my whole day playing around .. and I have no clue... what is happening on the build step

Debugging the production version using this modification : 

```js 
  function fixTarget (origin) {
    origin = bundlerOverrides[origin] || origin

    if (isAbsolute(origin) || origin.indexOf('file://') === 0) {
      return origin
    }

    if (origin === 'pino/file') {
      return join(__dirname, '..', 'file.js')
    }

    let fixTarget

    for (const filePath of callers) {
      try {
        const context = filePath === 'node:repl'
          ? process.cwd() + sep
          : filePath
        throw new Error(createRequire(context).resolve(origin))
        console.log(createRequire(context).resolve(origin))
        fixTarget = createRequire(context).resolve(origin)
        break
      } catch (err) {
        // Silent catch
        throw new Error(err)
        continue
      }
    }

    if (!fixTarget) {
      throw new Error(`unable to determine transport target for "${origin}"`)
    }

    return fixTarget
  }
}
```

shows that the @axiomhq\pino\dist\cjs\index.cjs' is what it tries to use. 

though in vite ".cjs" is depreciated and it should use ".mjs" 
also in the build output the "cjs" folder is deleted and doesn't exists, which causes this error.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

These bundling issues are quite tricky, so if you would like to also send a PR... that would be amazing.

**Comment by Bouchtaoui** [comment]
I have the exact same problem. I'm not able to give you a reproducible example at the moment. But it's fairly simple, just make a transport object for axiom and try deploy it on netlify or vercel and. you'll see the error yourself.

I jumped from Winston to Pino because of its asynchronous logging. But it doesn't work in production, sadly enough.

**Comment by ustad-nordin** [comment]
> Thanks for reporting!
> 
> Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
> 
> These bundling issues are quite tricky, so if you would like to also send a PR... that would be amazing.


I setup the following project to reproduce the problem:
https://github.com/ustad-nordin/axiom-error

I hope you have the time to look at it 👀

**Comment by caelinsutch** [comment]
Anyone figure out a workaround?

**Comment by ustad-nordin** [comment]
Hi there,

I ended up using Axiom without Pino. I don't want to depend on too many packages. The advantage of Pino is you can easily change transport to send your logging to another service.

**Comment by astanciu** [comment]
Also seeing this issue in Vercel, using @axiomhq/pino transport. Any updates?

**Comment by carsonb** [comment]
Also seeing this in Vercel with NextJS.
I attempted to incorporate `pino-webpack-plugin`, but ran into the same issue as https://github.com/pinojs/pino-webpack-plugin/issues/190
Also attempted the identified workaround in https://github.com/vercel/next.js/discussions/46987#discussioncomment-10397449 but no success

The reproducable example from 2 weeks ago in https://github.com/pinojs/pino/issues/1964#issuecomment-2267598355 matches how I am trying to use pino with a transport target

**Comment by magnusriga** [comment]
@carsonb I ended up getting the same issue as yourself in runtime (my setup turned out to only work build time).

**Error**: `TypeError: Cannot read properties of null (reading 'fn')`, when `pino` is included in the `config.externals` list, and `No template for dependency: CommonJsRequireDependency` when `pino` is not in `config.externals`.

**Comment by naz** [comment]
The `import '@axiomhq/pino'` fix worked for my case where I use Pino with NestJS running on Vercel environment

**Comment by sibteali786** [comment]
> Unable to Determine Transport Target for @logtail/pino in the Vercel Environment logtail/logtail-js#129

It alao helped me in my case where pino was throwing transport related error in my Turorepo monolith on Vercel. Thanks a lot @carsonb

**Comment by sibteali786** [comment]
> Also seeing this in Vercel with NextJS. I attempted to incorporate `pino-webpack-plugin`, but ran into the same issue as [pinojs/pino-webpack-plugin#190](https://github.com/pinojs/pino-webpack-plugin/issues/190) Also attempted the identified workaround in [vercel/next.js#46987 (comment)](https://github.com/vercel/next.js/discussions/46987#discussioncomment-10397449) but no success
> 
> The reproducible example from 2 weeks ago in [#1964 (comment)](https://github.com/pinojs/pino/issues/1964#issuecomment-2267598355) matches how I am trying to use pino with a transport target
> 
> EDIT: I've added a simple `import '@axiomhq/pino'` in the file where I use `@axiomhq/pino` as a string and **I'm no longer seeing the error**. This is a weird one! Might be a workaround for others. I am also listing all pino related packages in my NextJS config:
> 
> ```js
> module.exports = {
>   experimental: {
>     serverComponentsExternalPackages: [
>       'thread-stream',
>       'pino',
>       'pino-worker',
>       'pino-file',
>       'pino-pretty',
>       '@axiomhq/pino',
>     ],
>   },
> }
> ```
It alao helped me in my case where pino was throwing transport related error in my Turorepo monolith on Vercel. Thanks a lot @carsonb
