### ISSUE TITLE
default level:${defaultLevel} must be included in custom levels

### ISSUE THREAD

**Issue by Jhon-Mosk** [pinojs/pino#2039]
I'm using pino in my project. When I'm starting my app into docker container, I get error.

```sh
/usr/src/app/node_modules/pino/lib/levels.js:194
    throw Error(`default level:${defaultLevel} must be included in custom levels`)
    ^

Error: default level:"debug" must be included in custom levels
    at assertDefaultLevelFound (/usr/src/app/node_modules/pino/lib/levels.js:194:11)
    at pino (/usr/src/app/node_modules/pino/pino.js:161:3)
    at Object.<anonymous> (/usr/src/app/lib/logger.js:41:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/app/main.js:2:16)
```

I use image node:20.17.0-alpine

I found out that for correct operation you need to specify LOGGER_LEVEL in the environment variables. When running without a container, such problems do not occur.

**Comment by Jhon-Mosk** [comment]
pino congif
```js
const config = {
  level: PINO_LOG_LEVEL || "info",
  transport: {
    targets: [
      {
        target: "pino-pretty",
        level: "debug",
        options: {
          translateTime: "HH:MM:ss Z",
          ignore: "pid,hostname",
          colorize: true,
        },
      },
      {
        target: "pino-telegram-webhook",
        level: "error",
        options: {
          chatId: PINO_TG_ALERT_GROUP_ID,
          botToken: PINO_TG_ALERT_BOT_TOKEN,
          extra: {
            parse_mode: "HTML",
          },
        },
      },
    ],
  },
};
```
