### ISSUE TITLE
Memory issue and "flushSync took too long" error

### ISSUE THREAD

**Issue by tmart-ops** [pinojs/pino#2106]
**Environment**: Express app using pino 9.5.0, pino-http 10.3.0 running in a container in Kubernetes

**Issue**: After a certain amount of hours running, the app which logs about 20k logs per hour, stops outputting logs. For the next few hours the memory usage of the pod will climb and level off (~1.3GB) before outputting a ton of errors until the pod is manually restarted.

The issue crops up sometimes multiple times in a day and sometimes after a span of days. We run multiple replicas of the app and only one replica will have the issue at a time. 

I haven't found much information on the flushSync or memory related errors that are similar to this.
In the meantime we'll test out if the issue happens with synchronous logging.
Any help or suggestions would be appreciated. Thanks.

**Transport definition**
```
const transports = [
    {
        target: "pino/file",
        sync: false,
        options: { destination: 1, sync: false }
    }
];
```

**Initial error after memory usage reaches the point where it levels off**
```
Error in pino transport Error: _flushSync took too long (10s)
at flushSync (/usr/src/app/node_modules/thread-stream/index.js:531:13)
at writeSync (/usr/src/app/node_modules/thread-stream/index.js:468:7)
at ThreadStream.write (/usr/src/app/node_modules/thread-stream/index.js:249:9)
at Pino.write (/usr/src/app/node_modules/pino/lib/proto.js:217:10)
at Pino.LOG [as info] (/usr/src/app/node_modules/pino/lib/tools.js:62:21)
at onResFinished (/usr/src/app/node_modules/pino-http/logger.js:129:15)
at ServerResponse.onResponseComplete (/usr/src/app/node_modules/pino-http/logger.js:178:14)
at ServerResponse.emit (node:events:526:35)
at onFinish (node:_http_outgoing:1005:10)
at callback (node:internal/streams/writable:608:21)
```

**Subsequent errors - these spam the logs (about 2k every 5 minutes)**
```
Error in pino transport Error: the worker has exited
at ThreadStream.write (/usr/src/app/node_modules/thread-stream/index.js:238:19)	
at Pino.write (/usr/src/app/node_modules/pino/lib/proto.js:217:10)	
at Pino.LOG [as info] (/usr/src/app/node_modules/pino/lib/tools.js:71:21)	
[The rest of the stack trace varies depending on which method called the logger]
```

**Comment by mcollina** [comment]
@tmart-ops a few notes:

1. you don't need to use a transport if you are just writing to stdout, just use `pino.destination()`.
2. it seems you are creating the transport with `sync: true`, can you paste your full initialization code?

**Comment by tmart-ops** [comment]
@mcollina 
I may have edited the code right after you saw it but we have tried both async and sync settings, the issue occurs with both. I'll include the additional init code. The only notable modifications we have are setting hostname to undefined (to prevent logging hostname) and a custom logLevel.

```
import pino from "pino";

const transports = [
    {
        target: "pino/file",
        sync: false,
        options: { destination: 1, sync: false }
    }
];

const customLevels = {  critical: 60 };
const base = { hostname: undefined };

const transportsInstance = pino.transport({ targets: transports });

// Log Pino errors
transportsInstance.on("error", (err: unknown) => {
    console.error("Error in pino transport", err);
});

export const PinoLogger = pino({ customLevels, base }, transportsInstance);
```

**Comment by mcollina** [comment]
Can you include a full reproduction?

**Comment by alfeugds** [comment]
I created this codesandbox based on @tmart-ops comment to reproduce the issue, as I have a similar setup in my application.
https://codesandbox.io/p/sandbox/pino-issue-log-d7x3sp

The codesandbox's terminal i/o stream is slow enough that it makes it easy to reproduce the issue. The log size or the log interval in `./index.js` can be tweaked to emulate different scenarios. The different pino configs (transport, destination) can be tweaked in `./logger.js`.The "Flame Chart Visualizer" package can be installed and a JavaScript Debug Terminal can be opened to run `npm run start`.

![Screenshot Capture - 2025-01-10 - 13-29-13](https://github.com/user-attachments/assets/727f3e10-c524-4b76-b428-13fe7e17d76a)

I noticed that setting `sync: true` didn't really block the main thread, and the memory still creeps up. I was under the impression it should behave as a blocking operation but I may have misread the docs.

I need custom levels, formatters and serializers, and couldn't find a way to configure them all to be executed in a worker. I guess we'd still have issues if the stdio stream can't keep up with the log writing volume anyways?

**Comment by mcollina** [comment]
> I noticed that setting sync: true didn't really block the main thread, and the memory still creeps up. I was under the impression it should behave as a blocking operation but I may have misread the docs.

in pino.destination()/sonic-boom, setting it to sync: true  makes it call fs.writeSync(), which is synchronous and blocking in regards to the OS. However, we do not call fsync. Data to be written can be in OS level.

**Comment by mcollina** [comment]
@alfeugds I've actually never used codesandbox, so I would really need some more detailed instructions or a reproduction that I can run locally. Debugging something low level remotely in this way is _very_ hard.

---

What is happening in the OP report:

1. the transport worker crashes
2. logs are accumulated in the main process, causing a memory leak.

The fundamental thing we would need is to know _why_ the thread exited. There is likely a lurking bug somewhere.

To debug this, I would add a `process._rawDebug('>>>', err)` in both and see why the thread exits.

https://github.com/pinojs/thread-stream/blob/a08e354782ea9254b6c7bff67a0a744381eca6d1/lib/worker.js#L145-L159

Now, it might be exiting for some other reason too, and not cause and `'error'` event to be emitted. We should likely emit one anyway, so that it crashes the process (correctly).

That error _should_ likely going into https://github.com/pinojs/thread-stream/blob/a08e354782ea9254b6c7bff67a0a744381eca6d1/index.js#L369 and crash the process because there is no one listening to that.

I'll try a PR soon.

**Comment by mcollina** [comment]
I think this is _not a bug_. Essentially someone added:

```js

// Log Pino errors
transportsInstance.on("error", (err: unknown) => {
  console.error("Error in pino transport", err);
});
```

That is an _unrecoverable_ error, and if the program keeps going... it will eventually stop logging and likely leak memory.

This should probably documented somewhere.
