### ISSUE TITLE
passing Error in object results in emptry error

### ISSUE THREAD

**Issue by pkubat** [pinojs/pino#412]
If passing other objects with an error then the Error object will be empty `{}`, seem the error serializer only serializes error when passed as direct paramter.

sample:
```
const se = require('serialize-error')
const log = require('pino')()

const e1 = new Error('error #1')
const e2 = new Error('errror #2')

const o1 = { foo: 'bar'}

log.info(e1, 'just e1')
log.info({ e1 }, 'just e1 as object')
log.info({ e1, o1 }, 'e1 and o2');
// a work around
log.info({ error: se(e1), o1 }, 'e1 and o2 se');
```

results (`node src/lib/test.js | pino-pretty`):
```
[1525481147711] INFO (25141 on Reliance.local): just e1
    Error: error #1
        at Object.<anonymous> (/Users/Philip/Documents/Clients/Qwasi/Development/qChat/src/lib/test.js:8:12)
        at Module._compile (module.js:649:30)
        at Object.Module._extensions..js (module.js:660:10)
        at Module.load (module.js:561:32)
        at tryModuleLoad (module.js:501:12)
        at Function.Module._load (module.js:493:3)
        at Function.Module.runMain (module.js:690:10)
        at startup (bootstrap_node.js:194:16)
        at bootstrap_node.js:666:3
[1525481147712] INFO (25141 on Reliance.local): just e1 as object
    e1: {}
[1525481147712] INFO (25141 on Reliance.local): e1 and o2
    e1: {}
    o1: {
      "foo": "bar"
    }
[1525481147712] INFO (25141 on Reliance.local): e1 and o2 se
    error: {
      "name": "Error",
      "message": "error #1",
      "stack":
          Error: error #1
              at Object.<anonymous> (/Users/Philip/Documents/Clients/Qwasi/Development/qChat/src/lib/test.js:8:12)
              at Module._compile (module.js:649:30)
              at Object.Module._extensions..js (module.js:660:10)
              at Module.load (module.js:561:32)
              at tryModuleLoad (module.js:501:12)
              at Function.Module._load (module.js:493:3)
              at Function.Module.runMain (module.js:690:10)
              at startup (bootstrap_node.js:194:16)
              at bootstrap_node.js:666:3
    }
    o1: {
      "foo": "bar"
    }
```

**Comment by ilyaztsv** [comment]
@pkubat please see `--errorProps` option here: https://github.com/pinojs/pino/blob/master/docs/cli.md
