### ISSUE TITLE
pretty-print tries to mkdir $HOME, fails

### ISSUE THREAD

**Issue by hraban** [pinojs/pino#498]
hi all,

running pretty-print in Docker:

```
myuser@9137c53cf9fd:/usr/src/app$ echo '{"level":30,"time":1535020808810,"msg":"test message","pid":26,"hostname":"1f04a7b75784","v":1}' | npx pino-pretty
Error: EACCES: permission denied, mkdir '/home/myuser'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:224:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:262:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:178:20)
    at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:35:29
    at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:35:29
    at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:35:29
    at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:378:26)
Install for pino-pretty@latest failed with code 7
```

Does it need to mkdir /home/myuser? Can I disable whatever feature requires this in pretty-print, somehow?

thanks

**Comment by mcollina** [comment]
This is a bug with npx, not pino-pretty. Just run `npm install pino-pretty -g`.

**Comment by hraban** [comment]
You were right! Thanks for that, sorry about the spurious bugreport.
