### ISSUE TITLE
TypeError: Cannot create property 'Symbol(circular-ref-tag)' on string 'foo'

### ISSUE THREAD

**Issue by jiripospisil** [pinojs/pino#502]
```javascript
// kk.js
const pino = require("pino")();
pino.error({ err: "foo" }, "Something something...");
```

**v4.17.6**

```
/tmp/tp-20180824155606 ∴ node kk.js
{"level":50,"time":1535119815584,"msg":"Something something failed.","pid":76251,"hostname":"Jiri.local","err":"foo","v":1}
```

**v5.3.1**

```
/tmp/tp-20180824155606 ∴ node kk.js
/private/tmp/tp-20180824155606/node_modules/.registry.npmjs.org/pino-std-serializers/2.2.0/node_modules/pino-std-serializers/lib/err.js:8
  err[seen] = undefined // tag to prevent re-looking at this
            ^

TypeError: Cannot create property 'Symbol(circular-ref-tag)' on string 'foo'
    at Object.errSerializer [as err] (/private/tmp/tp-20180824155606/node_modules/.registry.npmjs.org/pino-std-serializers/2.2.0/node_modules/pino-std-serializers/lib/err.js:8:13)
    at Pino.asJson (/private/tmp/tp-20180824155606/node_modules/.registry.npmjs.org/pino/5.3.1/node_modules/pino/lib/tools.js:108:52)
    at Pino.write (/private/tmp/tp-20180824155606/node_modules/.registry.npmjs.org/pino/5.3.1/node_modules/pino/lib/proto.js:88:28)
    at Pino.LOG [as error] (/private/tmp/tp-20180824155606/node_modules/.registry.npmjs.org/pino/5.3.1/node_modules/pino/lib/tools.js:39:21)
    at Object.<anonymous> (/private/tmp/tp-20180824155606/kk.js:5:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

It looks like there's something significant about the property name `err` because it works with a different name.

```
> pino.error({ err2: "foo" }, "Bar")
{"level":50,"time":1535120014536,"msg":"Bar","pid":76269,"hostname":"Jiri.local","err2":"foo","v":1}
```

Node.js v10.9.0

**Comment by mcollina** [comment]
Thanks, it should be fixed now!

**Comment by jiripospisil** [comment]
Yup, works fine now. Thank you!
