### ISSUE TITLE
How use v5 with prettyPrint and pino-multi-stream? 

### ISSUE THREAD

**Issue by sheldhur** [pinojs/pino#530]
`
 const outStream = pino.pretty();
 outStream.pipe(process.stdout);
 streams.push({ level: options.level, stream: outStream });
 ...
 const logger = pino(options, streams && streams.length ? pinoms.multistream(streams) : process.stdout);
`
I want 3 streams for dev: pretty stdout, elasticsearch and rotating-file-stream.
It's will work in v4 becouse `pino` and `pino.pretty()` return stream. 

I'm trying get steram as
`
  const outStream = pino({prettyString: true});
  streams.push({ level: options.level, stream: outStream[pino.symbols.streamSym] });
`
but got an exception
`
(node:7822) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at Object.write (%projectname%/node_modules/pino/lib/tools.js:225:16)
    at Object.write (%projectname%/node_modules/pino-multi-stream/multistream.js:59:16)
    at Pino.write (%projectname%/node_modules/pino/lib/proto.js:99:15)
    at Pino.LOG (%projectname%/node_modules/pino/lib/tools.js:39:21)
    at catch.e (%projectname%/src/index.js:11:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at Object.<anonymous> (%projectname%/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
`

How I can do it now with v5?

**Comment by jimmiehansson** [comment]
No prior experience from Pino, although it seems like a great project to use.
A quick search in the codebase seems that pretty adheres to `prettyPrint` and not `prettyString`, is this correct?
https://github.com/pinojs/pino-pretty#options

**Comment by jsumners** [comment]
Correct. `prettyString` is not a valid option.

**Comment by sheldhur** [comment]
It's just a misprint in my example.

**Comment by rubenhak** [comment]
Guys, is this going to be fixed, or have to find some other way?

**Comment by sheldhur** [comment]
@rubenhak I'm think what found how fix it. Look in your thread.

**Comment by jsumners** [comment]
Sorry. This is not something I will ever have a need to do so it is not a priority for me with my limited time for OSS. I can review any PR you send in for this, though.

**Comment by sheldhur** [comment]
@jsumners check pls #555
