### ISSUE TITLE
Partial Prettyfier

### ISSUE THREAD

**Issue by rubenhak** [pinojs/pino#534]
Just like available in bunyan and winston, I would like to have ability to prettify the console output only, but keep the output to the file as json. Currently I'm using the following way:

```
const Pino = require('pino');
const multi = require('multi-write-stream');

var logFileStream = fs.createWriteStream('the-path');
var stream = multi([
    process.stdout,
    logFileStream
])

 var pinoOptions = {
    name: this._name,
    prettyPrint: {
        levelFirst: false,
        translateTime: true,
        colorize: true
    },
    prettifier: require('pino-pretty')
}

var logger = Pino(pinoOptions, stream);
```

P.S. I'm aware of the out-of-process prettyfier. In this particular case need to get console prettification in process.

**Comment by rubenhak** [comment]
It was suggested to move the request here. [https://github.com/pinojs/pino-pretty/issues/31](https://github.com/pinojs/pino-pretty/issues/31)

**Comment by mcollina** [comment]
This might require exposing some of the internals, but it should be doable.

It would need a combination of [getPrettyStream](https://github.com/pinojs/pino/blob/master/lib/tools.js#L168) with [pino-multi-stream](https://github.com/pinojs/pino-multi-stream). I think this would be a nice use case, and something that we should document.

Would you mind checking if the approach works, and in case we'll add `getPrettyStream` to our public API.

**Comment by rubenhak** [comment]
Are you referring to something like this?

```
const Pino = require('pino');
const PinoPretty = require('pino-pretty');
const PinoGetPrettyStream = require('pino/lib/tools').getPrettyStream;
const multi = require('multi-write-stream');

var prettyStream = PinoGetPrettyStream({
        levelFirst: false,
        translateTime: true,
        colorize: true
    },
    PinoPretty,
    process.stdout);

var logFileStream = fs.createWriteStream('the-path');

var stream = multi([
    prettyStream,
    logFileStream
])

 var pinoOptions = {
    name: this._name
}

var logger = Pino(pinoOptions, stream);
```

**Comment by mcollina** [comment]
Yes exactly, does it work?

Il giorno mar 23 ott 2018 alle 21:31 Ruben <notifications@github.com> ha
scritto:

**Comment by rubenhak** [comment]
Something not working right. There is some magic inside `prettifierMetaWrapper` that expects `this`.

```
const fs = require('fs');
const Pino = require('pino');
const PinoPretty = require('pino-pretty');
const PinoGetPrettyStream = require('pino/lib/tools').getPrettyStream;
const multistream = require('pino-multi-stream').multistream

var prettyStream = PinoGetPrettyStream({
        levelFirst: false,
        translateTime: true,
        colorize: true
    },
    PinoPretty,
    process.stdout);

var streams = [
    {stream: fs.createWriteStream('my.log') },
    // {stream: process.stdout }
    {stream: prettyStream }
]

var pinoOptions = {
    name: this._name
}
var logger = Pino(pinoOptions, multistream(streams));

logger.info("HELLO %s!", "World")
```

returns error:
```
node_modules\pino\lib\tools.js:225
      if (time.match(/^\d+/)) {
               ^

TypeError: Cannot read property 'match' of undefined
    at Object.write (D:\Repos\Berlioz.git\experiments\test-client\node_modules\pino\lib\tools.js:225:16)
    at Object.write (D:\Repos\Berlioz.git\experiments\test-client\node_modules\pino-multi-stream\multistream.js:59:16)
    at Pino.write (D:\Repos\Berlioz.git\experiments\test-client\node_modules\pino\lib\proto.js:99:15)
    at Pino.LOG [as info] (D:\Repos\Berlioz.git\experiments\test-client\node_modules\pino\lib\tools.js:40:26)
    at Object.<anonymous> (D:\Repos\Berlioz.git\experiments\test-client\index.js:26:8)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by mcollina** [comment]
There is possibly something to fix either here on in pino-multi-stream. Would you like to send a PR?

**Comment by rubenhak** [comment]
where should i send it?

**Comment by sheldhur** [comment]
Duplicate of #530

**Comment by sheldhur** [comment]
@mcollina I'm try fix it and can't found how I can get time in `prettifierMetaWrapper`. The only thing that I found it get time from JSON in chunk. If so I can send PR.

**Comment by rubenhak** [comment]
Thanks for fixes. I verified and it now works with pino v5.10.2.
