### ISSUE TITLE
Exception thrown when setting up redaction

### ISSUE THREAD

**Issue by gauravmk** [pinojs/pino#562]
I can get a repro with

```
const logger = require('pino')({
  redact: [
    'headers["x-secret-token"]',
    'headers["x-csrf-token"]',
    'headers.cookie',
    'headers.authorization',
    'headers.referer',
  ],
});

const fauxRequest = {
  headers: {
    host: 'http://example.com',
    cookie: `oh oh we don't want this exposed in logs in etc.`,
    referer: `if we're cool maybe we'll even redact this`,
    'x-csrf-token': 'test-token',
    'x-secret-token': 'secret',
  },
};

logger.warn(fauxRequest, 'test');
```

The exception thrown is
```
undefined:25
      if (o. && o.["x-csrf-token"] != null) {
             ^^

SyntaxError: Unexpected token &&
    at Function (<anonymous>)
    at redactor (/Users/gauravkulkarni/test/node_modules/fast-redact/lib/redactor.js:9:18)
    at fastRedact (/Users/gauravkulkarni/test/node_modules/fast-redact/index.js:45:10)
    at Object.keys.reduce (/Users/gauravkulkarni/test/node_modules/pino/lib/redaction.js:47:17)
    at Array.reduce (<anonymous>)
    at redaction (/Users/gauravkulkarni/test/node_modules/pino/lib/redaction.js:44:29)
    at pino (/Users/gauravkulkarni/test/node_modules/pino/pino.js:76:33)
    at Object.<anonymous> (/Users/gauravkulkarni/test/test-redact.js:1:93)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

I tried to check if it was an issue with `fast-redact` but weirdly

```
const redact = require('fast-redact')({
  paths: [
    'headers["x-secret-token"]',
    'headers["x-csrf-token"]',
    'headers.cookie',
    'headers.authorization',
    'headers.referer',
  ],
});

const fauxRequest = {
  headers: {
    host: 'http://example.com',
    cookie: `oh oh we don't want this exposed in logs in etc.`,
    referer: `if we're cool maybe we'll even redact this`,
    'x-csrf-token': 'test-token',
    'x-secret-token': 'secret',
  },
};

console.log(redact(fauxRequest));
```

runs perfectly fine

**Comment by jimmiehansson** [comment]
It seems you are attempting to redact a non object, hence there's no traversal since you're passing

```js
logger.warn(fauxRequest, 'test');
``` 
It would work on `fast-redact` as you're not passing a string literal, e.g.
So, remove the second arg, ```'test'``` and try again.

```js
console.log(redact(fauxRequest));
```
You'll need to pass an object to do this.
Hope this is of help

**Comment by davidmarkclements** [comment]
this has nothing to do with redacting a non-object, and removing the second arg will lead to the same area. 

No this is to do with the way `lib/redaction.js` is traversing paths through objects and passing them to fast-redact individually (it's not properly handling square brackets)

**Comment by davidmarkclements** [comment]
@gauravmk fast redact 1.4.1 was just released, if you simply reinstall deps it should work for you now - thanks for reporting!

**Comment by jimmiehansson** [comment]
@davidmarkclements Thanks for clarifying, that should had been tested to verify on my end.
It makes sense looking at it. Do you mean the `brackets` as previously mentioned from how `fast-redact` retrieves the values of the brackets per element like below where its encapsulated as string?

```
i-> { headers: [] }
r-> []
i-> { headers: [ '["x-secret-token"]' ] }
r-> [ '["x-secret-token"]' ]
i-> { headers: [ '["x-secret-token"]', '["x-csrf-token"]' ] }
r-> [ '["x-secret-token"]', '["x-csrf-token"]' ]
i-> { headers: [ '["x-secret-token"]', '["x-csrf-token"]', 'cookie' ] }
r-> [ '["x-secret-token"]', '["x-csrf-token"]', 'cookie' ]
i-> { headers:
   [ '["x-secret-token"]',
     '["x-csrf-token"]',
     'cookie',
     'authorization' ] }
r-> [ '["x-secret-token"]',
  '["x-csrf-token"]',
  'cookie',
  'authorization' ]
```

**Comment by gauravmk** [comment]
Thanks! works like a charm.
