### ISSUE TITLE
Log functions throw TypeError for some inputs

### ISSUE THREAD

**Issue by hbacelar** [pinojs/pino#595]
version: 5.10.6
node: v10.14.2

Pino log functions throw an Error for some edge inputs.

Input:
```
pino.info({key: 'val'}, undefined);
```
Throws:
```
TypeError: Cannot read property 'length' of undefined
    at format (node_modules/quick-format-unescaped/index.js:31:16)
    at Pino.LOG [as info] (node_modules/pino/lib/tools.js:34:25)
```
Input:
```
pino.info(undefined, 'message');
```
Throws:
```
TypeError: Cannot read property 'length' of undefined
    at format (node_modules/quick-format-unescaped/index.js:31:16)
    at Pino.LOG [as info] (node_modules/pino/lib/tools.js:35:33)

```
Input:
```
pino.info(undefined, undefined);
```
Throws:
```
TypeError: Cannot read property 'length' of undefined
    at format (node_modules/quick-format-unescaped/index.js:31:16)
    at Pino.LOG [as info] (node_modules/pino/lib/tools.js:35:33)

```
Input:
```
pino.info(null, null);
```
Throws:
```
TypeError: Cannot read property 'length' of null
    at format (node_modules/quick-format-unescaped/index.js:31:16)
    at Pino.LOG [as info] (node_modules/pino/lib/tools.js:35:33)

```
Input:
```
pino.info({key: 'val'}, null);
```
Throws:
```
TypeError: Cannot read property 'length' of null
    at format (node_modules/quick-format-unescaped/index.js:31:16)
    at Pino.LOG [as info] (node_modules/pino/lib/tools.js:34:25)

```
Input:
```
const err = new Error('internal error messsage');
pino.error(err, err.msg);
```
Throws:
```
TypeError: Cannot read property 'length' of undefined
    at format (node_modules/quick-format-unescaped/index.js:31:16)
    at Pino.LOG [as error] (node_modules/pino/lib/tools.js:34:25)
```
I don't know if this is the expected behavior.

**Comment by mcollina** [comment]
Most of those are expected, and they would classify as dev errors. If you would like to remove those, we will be happy to review a PR that does not worsen our benchmarks.

**Comment by davidmarkclements** [comment]
OR - even just catching and throwing more useful errors would be good

**Comment by hbacelar** [comment]
I've opened a [PR](https://github.com/davidmarkclements/quick-format-unescaped/pull/23) on quick-format-unescaped module.

If this PR is correct pino will not throw on the posted cases.

**Comment by davidmarkclements** [comment]
amazing @hbacelar thank you for that, quick-format-unescpaed 3.0.2 was just released with your patch
