### ISSUE TITLE
undefined child bindings results in error

### ISSUE THREAD

**Issue by jcald1** [pinojs/pino#619]
# Summary
If you submit an `undefined` parameter in child(), the application errors out.

Code
```
const logger = require('pino')(undefined) // This one is OK

logger.info('hello world')

const child = logger.child(undefined) // Error
child.info('hello child!')

```

Submitting `undefined` in the pino options does not cause an error.  

# Expected Result
You should be able to submit undefined, null, or an empty object in the pino options and child bindings.

# Error
```
Error: missing bindings for child Pino
    at asChindings (/Users/user/projects/businesswire/backend/connect5-mediapipeline/temp/node_modules/pino/lib/tools.js:139:11)
    at Pino.child (/Users/user/projects/businesswire/backend/connect5-mediapipeline/temp/node_modules/pino/lib/proto.js:66:21)
    at Object.<anonymous> (/Users/user/projects/businesswire/backend/connect5-mediapipeline/temp/index.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19
```

**Comment by jsumners** [comment]
The bindings for the child logger are what give indication it is a child logger.

**Comment by davidmarkclements** [comment]
Perhaps the error message could be improved, PR welcome there and to docs. But child bindings must be an object.
