### ISSUE TITLE
Unexpected token % on node 12

### ISSUE THREAD

**Issue by tuananh** [pinojs/pino#668]
No issue on node 10 though

I got this as soon as I tried node 12.4.0

```
SyntaxError: Unexpected token %",
            "    at actualWrite (/Users/anh/code/myapp/node_modules/sonic-boom/index.js:242:3)",
            "    at SonicBoom.write (/Users/anh/code/myapp/node_modules/sonic-boom/index.js:142:5)",
            "    at Pino.write (/Users/anh/code/myapp/node_modules/pino/lib/proto.js:136:43)",
            "    at Pino.LOG [as fatal] (/Users/anh/code/myapp/node_modules/pino/lib/tools.js:34:21)",
            "    at formatError (/Users/anh/code/myapp/index.js:107:13)",

            
```
the code that's responsible for the above error

```
    formatError: err => {
        // log and rethrow
        log.fatal({ name: 'queryError' }, err)
        throw err
    }
```

**Comment by tuananh** [comment]
ah I was using older version of pino 5.12.3

Upgrading to 5.12.6 fixes it.

**Comment by eran10** [comment]
still happens with pino 5.13.5..

**Comment by davidmarkclements** [comment]
remove your package-lock and node_modules and reinstall

**Comment by eran10** [comment]
thanks will check!
