### ISSUE TITLE
Unexpected Token % Syntax Error

### ISSUE THREAD

**Issue by natanavra** [pinojs/pino#680]
Happens inside a `then` block on Node v12.3.1 only when running in debug mode.
Seems like something new after updating node version

Looks like this:
```
return databaseLoader.then(function() {
	middlewares.load(app);
	return app.listen(PORT);
}).then(serv => {
	server = serv;
	logger.info({ info }, 'server up'); // <--- this throws
	return app;
})

SyntaxError: Unexpected token %
    at Pino.write (/server/node_modules/pino/lib/proto.js:137:21)
    at Pino.LOG [as error] (/server/node_modules/pino/lib/tools.js:34:21)
    at process.<anonymous> (/server/server.js:68:10)
    at process.emit (events.js:200:13)
    at processPromiseRejections (internal/process/promises.js:165:18)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
undefined:3
return typeof s === "string" ? %FlattenString(s) : s
```

**Comment by davidmarkclements** [comment]
*only* when in debug mode? Oh lawd.

A quick fix here, when running in debug mode add an additional flag, `--allow-natives-syntax`:

```
node --inspect --allow-natives-syntax app.js
```

**Comment by natanavra** [comment]
Yup, actually looks like a dependency called `flatstr` is the culprit:
```
'use strict'

if (!process.versions || !process.versions.node || parseInt(process.versions.node.split('.')[0]) >= 8) {
  try { 
    var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s') // <--- this
  } catch (e) {
    try { 
      var v8 = require('v' + '8')
      v8.setFlagsFromString('--allow-natives-syntax')
      var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s') // <--- OR this
      v8.setFlagsFromString('--no-allow-natives-syntax')
      process.nextTick(flatstr, '')
    } catch (e) {
      var flatstr = function flatstr(s) {
        Number(s)
        return s
      }
    }
  }
} else flatstr = function flatstr(s) {
  Number(s)
  return s
}

module.exports = flatstr
```

**Comment by davidmarkclements** [comment]
yeah I know I wrote `flatstr` - it's a reoccurring issue because of changes to the JS engine, did the command flag for you re debugging?

**Comment by natanavra** [comment]
Yup, works with the flag

**Comment by davidmarkclements** [comment]
oh wait hold on a second - that's an old version of flatstr.

if you do a `rm -fr node_modules` you shouldn't need the flag any more (unless you're using a very old pino version)

**Comment by davidmarkclements** [comment]
this is the new flatstr https://github.com/davidmarkclements/flatstr/blob/master/index.js (which side steps the problem entirely)

**Comment by natanavra** [comment]
Thanks @davidmarkclements 
I've actually did an `npm install --save pino@latest` trying to tackle the issue but it probably didn't refresh the dependency
