### ISSUE TITLE
TypeError: Cannot read property 'labels' of undefined

### ISSUE THREAD

**Issue by wanglong167** [pinojs/pino#833]
```js
//test.js
const pino = require('pino')();

process.on('warning', (warning) => {
  pino.info(warning);
});
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})

```

  return levels.labels[levelVal]
               ^

TypeError: Cannot read property 'labels' of undefined

**Comment by jsumners** [comment]
For the audience: the provided reproduction is triggering an `EventEmitter` memory leak warning by registering too many listeners. Within the warning handler the Pino instance is attempting to stringify the `warning` object and triggers a reference error:

```
❯ node index.js
(node:14690) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 foo listeners added to [process]. Use emitter.setMaxListeners() to increase limit
/private/tmp/07/node_modules/pino/lib/levels.js:115
  return levels.labels[levelVal]
                ^

TypeError: Cannot read property 'labels' of undefined
    at EventEmitter.getLevel (/private/tmp/07/node_modules/pino/lib/levels.js:115:17)
    at EventEmitter.get level [as level] (/private/tmp/07/node_modules/pino/lib/proto.js:54:42)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:58:19)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:52:9)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:52:9)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at decirc (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at stringify (/private/tmp/07/node_modules/pino/node_modules/fast-safe-stringify/index.js:11:3)
```

**Comment by mcollina** [comment]
There is a circular reference in the `warning`  object that it seems we are failing to address. This should fix it:

```js
const pino = require('.')();

process.on('warning', (warning) => {
  warning.emitter = null // avoid the circular reference
  pino.info(warning);
});
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
process.on('foo', () => {});
process.on('foo', () => {})
```

**Comment by niftylettuce** [comment]
I also reproduced this issue.

```sh
Cannot read property 'labels' of undefined
TypeError: Cannot read property 'labels' of undefined
   at EventEmitter.getLevel (/var/www/production/source/node_modules/pino/lib/levels.js:115:17)
   at EventEmitter.get level [as level] (/var/www/production/source/node_modules/pino/lib/proto.js:54:42)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:19)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:52:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
   at decirc (/var/www/production/source/node_modules/fast-safe-stringify/index.js:58:9)
```

**Comment by niftylettuce** [comment]
Could we get this patched?  Thank you! 🙏

**Comment by mcollina** [comment]
A PR to fix this in `decirc` would be handy!

**Comment by Zirak** [comment]
This seems to be a problem with stringifying a pino export because of the `level` getter in the `proto.js` export.

Looking at the stack trace and what `decirc` is trying to stringify, it attempts to stringify `warning.emitter`, which is `process`, eventually leading to:

```
warning.emitter.mainModule.children[0].children[3].exports.level
//        ^ process            pino ^           ^ proto.js
```

Repro:

```
const pino = require('.')();
pino.info(require('./lib/proto'));

// or, more simply:

require('./lib/proto').level;
```

While this is triggered within pino code, it's not something unique to pino or a bug in how pino is written. One can imagine how other modules with getters will exhibit the same behaviour.

Will it be interesting for pino to handle such cases?

**Comment by mcollina** [comment]
I would call:

```

pino.info(require('./lib/proto'));
```

Something that should not really be done. If we could have some protection against it it would be handy and nice (maybe a `.toJSON()`?)

**Comment by Zirak** [comment]
pino isn't really the one at fault here, it could have happened with any other getter on a package export used unexpectedly. Contrived example:

```js
// foo.js
module.exports = {
    get foo() {
        throw new Error('sad');
    },
};

// main.js
const foo = require('./foo');
const stringify = require('fast-safe-stringify');
stringify(process);
```

Gives us the same sort of exception:

```
> node main.js 
/home/me/sources/pino/foo.js:3
        throw new Error('sad');
        ^

Error: sad
    at Object.get foo [as foo] (/home/me/sources/pino/foo.js:3:15)
    at decirc (/home/me/sources/pino/node_modules/fast-safe-stringify/index.js:58:19)
    at decirc (/home/me/sources/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at decirc (/home/me/sources/pino/node_modules/fast-safe-stringify/index.js:52:9)
    at decirc (/home/me/sources/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at decirc (/home/me/sources/pino/node_modules/fast-safe-stringify/index.js:58:9)
    at stringify (/home/me/sources/pino/node_modules/fast-safe-stringify/index.js:11:3)
    at Object.<anonymous> (/home/me/sources/pino/main.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

This can be treated either as a `fast-safe-stringify` bug, or a known limitation in said package which pino can handle. 
Stringifying a module object is such a weird situation though, it may not be worth pursuing.

**Comment by mcollina** [comment]
I don't think this is fixable. However I think we should protect our logs method from crashing. Essentially, we should another try-catch in https://github.com/pinojs/pino/blob/afb639c79a1135790e9302b94f054a6118bffa6f/lib/tools.js#L401 so that we can give up nicely and return a default string.
