### ISSUE TITLE
Pino + NextJs

### ISSUE THREAD

**Issue by sai1139** [pinojs/pino#840]
Pino is compatibility with NextJs

**Comment by mcollina** [comment]
It should be!

**Comment by sai1139** [comment]
i have tried but it was working  browser console . i don't know want there it should be nextjs console output.

**Comment by mcollina** [comment]
I don't understand. Can you create a repository to reproduce your problem?

**Comment by sai1139** [comment]
i will create a respository. give me some time .can you add PR

**Comment by sai1139** [comment]
@mcollina download this https://github.com/sai1139/pino-nextjs.git
1) install packages -> npm dev/yarn dev
2)in page, click on button .after clicking in browser console log message. same message i want in nextjs output console

**Comment by sai1139** [comment]
@mcollina any update?

**Comment by baterson** [comment]
Next.js console shows output during server-side rendering. When you call `onSubmit` handler it executes in a browser environment, not in the server so Pino is not an issue there.
For example, you can call Pino in the component body and it will log the message during SSR.
```
export const  Home = () => {
  Pino({}).info({ name: 'John Doe' });
  // ...
}
```

**Comment by mcollina** [comment]
You can follow the discussion in https://github.com/pinojs/pino-nextjs-example/pull/1/files.

**Comment by sai1139** [comment]
but every component will not be SSR,In that case.

**Comment by Vadorequest** [comment]
Pino completely breaks Next.js

Next.js is isomorphic and runs server side and client side.

```
TypeError: pino__WEBPACK_IMPORTED_MODULE_0___default(...)(...) is not a function
    at eval (webpack-internal:///./src/utils/logger.ts:5:109)
    at Module../src/utils/logger.ts (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:479:1)
    at __webpack_require__ (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:23:31)
    at eval (webpack-internal:///./src/components/appBootstrap/MultiversalAppBootstrap.tsx:25:72)
    at Module../src/components/appBootstrap/MultiversalAppBootstrap.tsx (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:217:1)
    at __webpack_require__ (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:23:31)
    at eval (webpack-internal:///./src/pages/_app.tsx:23:107)
    at Module../src/pages/_app.tsx (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:312:1)
    at __webpack_require__ (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:502:18)
    at __webpack_require__ (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:23:31)
    at /Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/vadorequest/dev/next-right-now/.next/server/static/development/pages/_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)


```

**To reproduce:**

1. git clone https://github.com/UnlyEd/next-right-now.git nrn-quick-start - Clones the boilerplate
1. cd nrn-quick-start && git checkout logger-pino - Working branch
1. yarn - Installs all deps from package.json
1. yarn start - Starts the app on http://localhost:8888/

Commenting out the line https://github.com/UnlyEd/next-right-now/pull/83/files#diff-9cf0826b88e28a9db80f768366ef2986R30 "unbreaks" the app.

**Comment by mcollina** [comment]
@Vadorequest check out https://github.com/pinojs/pino-nextjs-example/pull/1/files. As you can see, pino works well with next. I’m not sure what’s the problem of your webpack config.

**Comment by Vadorequest** [comment]
This relies on a custom server, which over-complexifies things and is not compatible with the Serverless way of running Next.js.

Also, logs written in the browser are sent to the server, maybe that's the point of the example, but that's weird. And overriding the `logger` per page (on the server side) is quite redundant.

But indeed it doesn't seem to suffer from a webpack issue.

**Comment by kelly-tock** [comment]
> This relies on a custom server, which over-complexifies things and is not compatible with the Serverless way of running Next.js.
> 
> 
> 
> Also, logs written in the browser are sent to the server, maybe that's the point of the example, but that's weird. And overriding the `logger` per page (on the server side) is quite redundant.
> 
> 
> 
> But indeed it doesn't seem to suffer from a webpack issue.

What do you recommend instead then?
