### ISSUE TITLE
PIno combining logs from multiple sessions, somehow

### ISSUE THREAD

**Issue by jontroncoso** [pinojs/pino#902]
I'm getting this log coming through. Notice the redundant `args` at the bottom. This is happening accross multiple requests:

```json
{"level":50,"time":1599035888485,"args":{"credentials":{"username":"jon.smith@anonymized.com","password":"!@#123QWEqwe","device":null}},"creation":{"timestamp":1598997216096,"stack":["at decoratedResolver (/opt/consumer/dist/graphql/index.js:100:58)","at field.resolve (/opt/consumer/node_modules/graphql-extensions/dist/index.js:134:26)","at field.resolve (/opt/consumer/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)","at resolveFieldValueOrError (/opt/consumer/node_modules/graphql/execution/execute.js:467:18)","at resolveField (/opt/consumer/node_modules/graphql/execution/execute.js:434:16)","at /opt/consumer/node_modules/graphql/execution/execute.js:244:18","at /opt/consumer/node_modules/graphql/jsutils/promiseReduce.js:23:10","at Array.reduce (<anonymous>)","at promiseReduce (/opt/consumer/node_modules/graphql/jsutils/promiseReduce.js:20:17)","at executeFieldsSerially (/opt/consumer/node_modules/graphql/execution/execute.js:241:37)","at executeOperation (/opt/consumer/node_modules/graphql/execution/execute.js:219:55)","at executeImpl (/opt/consumer/node_modules/graphql/execution/execute.js:104:14)","at Object.execute (/opt/consumer/node_modules/graphql/execution/execute.js:64:35)","at /opt/consumer/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","at Generator.next (<anonymous>)","at /opt/consumer/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","at new Promise (<anonymous>)","at __awaiter (/opt/consumer/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)","at execute (/opt/consumer/node_modules/apollo-server-core/dist/requestPipeline.js:228:20)","at Object.<anonymous> (/opt/consumer/node_modules/apollo-server-core/dist/requestPipeline.js:176:42)","at Generator.next (<anonymous>)"]},"args":{"credentials":{"username":"jon.smith@anonymized.com","password":"!@#123QWEqwe","device":null}},"args":{"credentials":{"username":"vban","password":"0w$pldF1c^C0sOvn","device":null}},"args":{"credentials":{"username":"vban","password":"0w$pldF1c^C0sOvn","device":null}},"args":{"credentials":{"username":"vban","password":"dgesg","device":null}},"args":{"credentials":{"username":"gdgrds","password":"hdrshdrsh","device":null}},"args":{"credentials":{"username":"TESTERONI","password":"INORETSET","device":null}},"args":{"credentials":{"username":"TEST","password":"TEST","device":null}},"args":{"credentials":{"username":"HELLO","password":"CLOUDWATCH","device":null}},"args":{"credentials":{"username":"EH","password":"EH","device":null}},"args":{"credentials":{"username":"EH","password":"E","device":null}},"args":{"credentials":{"username":"hello","password":"hello","device":null}},"args":{"credentials":{"username":"HELLO","password":"HELLO","device":null}},"args":{"credentials":{"username":"HELLO","password":"PLS","device":null}},"args":{"credentials":{"username":"GSDGSD","password":"GSEGSEG","device":null}},"args":{"credentials":{"username":"TEST","password":"TEST","device":null}},"duration":38672389,"error":{"message":"invalid_credentials","stack":["UserInputError: invalid_credentials","at Object.invalidCredentials (/opt/consumer/dist/graphql/session-create-response/index.js:8:11)","at exports.mutationSessionCreate (/opt/consumer/dist/graphql/session/mutation-session-create.js:107:43)"],"name":"UserInputError"}}
```

I use a JS wrapper around pino. Only this wrapper is ever used (pino is never imported directly):
```js
require('dotenv').config();
import P from 'pino';
import PinoHttp from 'express-pino-logger';

export function sanitizeObject(obj: {
  [key: string]: any;
}): { [key: string]: any } {
  // For use with processor if `id` is set and `idType` is ssn or pan.
  if (
    typeof obj === 'object' &&
    ['string', 'number'].includes(typeof obj?.id) &&
    [0, 2].includes(obj.idType)
  ) {
    obj.id = '*' + obj.id.toString().slice(-4);
  }

  // Anonymize any object property with any of these keys
  const fieldsToAnonymize = [
    'ssn',
    'accountNo',
    'account_no',
    'password',
    'oldPassword',
    'newPassword',
    'confirmNewPassword',
  ];
  for (const key of Object.keys(obj)) {
    // if its an object, sanitize
    if (typeof obj[key] === 'object' && Boolean(obj['key'])) {
      obj[key] = sanitizeObject(obj[key]);

      // If it's not, but it requires anonymizing, anonymize.
    } else if (
      fieldsToAnonymize.includes(key) &&
      ['string', 'number'].includes(typeof obj[key])
    ) {
      obj[key] = '*' + obj[key].toString().slice(-4);
    }
  }
  return obj;
}

export function createLogger(base: { [key: string]: any } = {}): P.Logger {
  const fakeError = new Error();
  const timestamp = Date.now();
  return P({
    base: {
      ...sanitizeObject(base),
      creation: {
        timestamp,
        stack: fakeError.stack.split(/[\n\r]\s+/).slice(2),
      },
    },
    mixin: () => {
      return {
        duration: Date.now() - timestamp,
      };
    },
    prettyPrint: process.env.NODE_ENV !== 'production',
  });
}

export function createClassLogger(
  thisClass,
  params: { [key: string]: any } = {},
): P.Logger {
  const className = thisClass?.constructor?.name ?? 'unknown';
  return createLogger({ className, params });
}
export function createGraphqlLogger({
  query,
  mutation,
  variables,
  options,
}: { [key: string]: any } = {}): P.Logger {
  const source = Boolean(query) ? query : mutation;
  // Try to get the top-level definition which tells us which mutation is being executed.
  const operation = source.definitions.find(
    d => d.kind === 'OperationDefinition',
  );
  return createLogger({
    variables,
    options,
    // Use just the name.
    operation: operation.name.value,
    operationType: Boolean(query) ? 'query' : 'mutation',
  });
}

export function createGrpcLogger(
  request: { [key: string]: any } | null,
): P.Logger {
  return createLogger({ request });
}

export function createExpressLoggerMiddleware(
  log?: P.Logger,
  base: { [key: string]: any } = {},
): PinoHttp.HttpLogger {
  return PinoHttp(log ?? createLogger(base));
}

export function logCaughtError(
  log: P.Logger,
  error: Error,
  options?: string | { [key: string]: any },
  errorMessage?: string,
): void {
  if (typeof options === 'string') {
    errorMessage = (errorMessage ?? '') + options;
    options = {};
  }
  log.error(
    {
      error: {
        message: error.message,
        stack: error.stack.split(/[\n\r]\s+/),
        name: error.name,
      },
      ...options,
    },
    errorMessage,
  );
}
```

And I use it like so:

```
function someFunction(paramA, paramB){ 
    const log = createLogger({paramA, paramB});
    const someObject = someOtherFunction(paramA, paramB);
    log.info({someObject}, 'This is a message!');

    try {
        doSomethingThatMightError(someObject, paramB);
    } catch(error) {
        logCaughtError(log, error, 'Notice how I pass the log which has paramA and paramB bound!');
        callback(new Error()); // or whatever...
    }
}
```

I don't even understand how this is possible.

**Comment by mcollina** [comment]
I'm not necessarily sure as you are doing a lot of things that are outside best practices.

Can you prepare an example __that we can run__ that have a fail/not fail result?

**Comment by jontroncoso** [comment]
Yeah. This was on the fault of the code that was written. It was reusing the same logger and extending it via `.child()` for every request. (I didn't write it).

I'm going to close this ticket since it was user-error and not the library's fault
