### ISSUE TITLE
Pino fails to load on node 14.15.1 and TS 4.1.2

### ISSUE THREAD

**Issue by anonrig** [pinojs/pino#935]
Here's the following stack trace:

```
error Uncaught Exception received! TypeError: Cannot read property 'level' of undefined
    at genLsCache (/Users/yagiz/Projects/PROJECT/node_modules/pino/lib/levels.js:55:45)
    at Object.pino [as default] (/Users/yagiz/Projects/PROJECT/node_modules/pino/pino.js:175:3)
    at Object.<anonymous> (/Users/yagiz/Projects/PROJECT/src/library/logger.ts:28:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/yagiz/Projects/PROJECT/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yagiz/Projects/PROJECT/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/yagiz/Projects/PROJECT/src/consumer.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/yagiz/Projects/PROJECT/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yagiz/Projects/PROJECT/node_modules/ts-node/src/index.ts:1059:12) +0ms
```

My tsconfig is:
```json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "lib": ["ES2015", "ES6"],
    "rootDir": "./src",
    "outDir": "./build",
    "esModuleInterop": true,
    "strict": true,
    "sourceMap": true,
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules"
  ]
}
```

my logger file:
```typescript
import Pino from 'pino'
export default Pino()
```

Here's my dependencies for you to reproduce:

```json
  "dependencies": {
    "pino": "^6.7.0"
  },
  "devDependencies": {
    "@types/amqplib": "^0.5.16",
    "@types/couchbase": "^2.4.2",
    "@types/node": "^14.14.12",
    "@types/pino": "^6.3.4",
    "@typescript-eslint/eslint-plugin": "^4.9.1",
    "@typescript-eslint/parser": "^4.9.1",
    "dotenv": "^8.2.0",
    "eslint": "^7.15.0",
    "eslint-config-google": "^0.14.0",
    "nodemon": "^2.0.6",
    "pino-pretty": "^4.3.0",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.2"
  }
```

**Comment by mcollina** [comment]
can you reproduce with just javascript? TS is not (yet) officially supported.

**Comment by mcollina** [comment]
can you also include what's the compiled js code?

**Comment by anonrig** [comment]
Compiled version of logger.ts is:

```javascript
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const pino_1 = __importDefault(require("pino"));
exports.default = pino_1.default();
//# sourceMappingURL=logger.js.map
```

**Comment by anonrig** [comment]
OK it seems that this is a typescript specific problem. it seems that symbols are somehow removed/buggy after compilation.

On node 14 the following did worked perfectly:

- logger.mjs
```javascript
import pino from 'pino'
export default pino({
  prettyPrint: true
})
```

- index.mjs
```javascript
import logger from './logger.mjs'
logger.info('hello world')
```

**Comment by anonrig** [comment]
I've found the problem, but not the solution. Here's my inspection:

in pino.js the following code causes the issue and even though formattersSym is Symbol(pino.formatters), formatters key isn't set:

```javascript
  Object.assign(instance, {
    levels,
    [useOnlyCustomLevelsSym]: useOnlyCustomLevels,
    [streamSym]: stream,
    [timeSym]: time,
    [timeSliceIndexSym]: timeSliceIndex,
    [stringifySym]: stringify,
    [stringifiersSym]: stringifiers,
    [endSym]: end,
    [formatOptsSym]: formatOpts,
    [messageKeySym]: messageKey,
    [nestedKeySym]: nestedKey,
    [serializersSym]: serializers,
    [mixinSym]: mixin,
    [chindingsSym]: chindings,
    [formattersSym]: allFormatters,
    [hooksSym]: hooks,
    silent: noop
  })
```

I've logged allFormatters variable before this line and the result is:

```javascript
{
  level: [Function: level],
  bindings: [Function: bindings],
  log: undefined
}
```

but after object.assign the instance doesn't have any formatters key:

```javascript
EventEmitter {
  levels: {
    labels: {
      '10': 'trace',
      '20': 'debug',
      '30': 'info',
      '40': 'warn',
      '50': 'error',
      '60': 'fatal'
    },
    values: { trace: 10, debug: 20, info: 30, warn: 40, error: 50, fatal: 60 }
  },
  silent: [Function: noop]
}
```
