### ISSUE TITLE
logging with pino on promise catch 

### ISSUE THREAD

**Issue by emilsivervik** [pinojs/pino#956]
Hello, 

Thanks for the awesome product and the work you're doing!

I've stumbled upon a problem which I don't really know if it's just an implementation that you don't support or not but I thought I'd ask you instead.

Code to reproduce
```javascript
const logger = require('pino')()

const test = () => {
  return Promise.reject(new Error('dogs running'))
}

test()
  .catch(logger.error)
```
Error:
```
TypeError: Cannot read property 'Symbol(pino.nestedKey)' of undefined
    at LOG (/node/node_modules/pino/lib/tools.js:47:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The above snippet does with with `console.error` and gives me 
```
Error: dogs running
    at test (/node/test.js:4:25)
    at Object.<anonymous> (/node/test.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

So my question is if this is a bug or if it's not just intended use?

I know that using `catch(err => logger.error(err))` works just fine, I just thought it would be prettier with a shorthand

**Comment by davidmarkclements** [comment]
The logger methods rely on being called on the logger (for performance
reasons).

Passing logger.error.bind(logger) to catch will solve this.
