### ISSUE TITLE
Understanding how formatters and serializers work

### ISSUE THREAD

**Issue by btilford** [pinojs/pino#991]
Sorry I know you get a lot of these questions but every time I think I understand how things are going to be output it's not what I expected.

I'm trying to figure out why (in Stackdriver) the merge object is empty except for the things set during logger creation. And why I don't ever see error information logged. I may very well have a plugin or misconfiguration, but I've spent hours and hours over the last 6 months coming back to this.

Should `logger.error({err, prop1: '123'}, 'Error!!! %s', err.message)` end up outputting something like.

```json
{
 "level": 50,
  "time": 1616629624712,
  "err": {"message": "<error message>", "stack": "<stack\ntrace>" },
  "prop1" : "123",
  "name": "<set when logger was created>",
  "req": { "headers": {}, "url": "<>", "method": "GET" },
  "message" : "Error!!! <error message>",
}
```

Currently, my output omits both `err` and `prop1`

```json
{
 "level": 50,
  "time": 1616629624712,
  "name": "<set when logger was created>",
  "req": { "headers": {}, "url": "<>", "method": "GET" },
  "message" : "Error!!! <error message>",
}
```

**Comment by jsumners** [comment]
Can you provide a full reproduction? I am not seeing this issue.

**index.js**
```js
const log = require('pino')()

const err = Error('boom')
log.info({ err, foo: 'foo' }, 'Error!!! %s', err.message)
```


```
❯ node index.js | jq
{
  "level": 30,
  "time": 1616673421539,
  "pid": 90316,
  "hostname": "mini2018",
  "err": {
    "type": "Error",
    "message": "boom",
    "stack": "Error: boom\n    at Object.<anonymous> (/private/tmp/25/index.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47"
  },
  "foo": "foo",
  "msg": "Error!!! boom"
}
```
